"""A PEP517/660-compliant build backend for Bertrand projects, which runs an
instrumented CMake build to detect and compile C++ dependencies, and generate bindings
to back cross-language imports.
"""
from __future__ import annotations

from pathlib import Path
from typing import Mapping, Sequence

import setuptools.build_meta

from .run import run


ARTIFACT_ROOT = Path("/tmp/bertrand/artifacts")
CONANFILE = ARTIFACT_ROOT / "conanfile.py"
CONAN_OUTPUT = ARTIFACT_ROOT / "conan"


type PEP517ConfigValue = str | Sequence[str]
type ConfigSettings = Mapping[str, PEP517ConfigValue] | None
type SetuptoolsConfigValue = str | list[str] | None
type SetuptoolsConfigSettings = dict[str, SetuptoolsConfigValue] | None


def _conan_install(*, quiet: bool) -> None:
    if not CONANFILE.exists() or not CONANFILE.is_file():
        return  # python-only builds can proceed without Conan artifacts
    run([
        "conan",
        "install",
        str(CONANFILE),
        "--profile:host=default",  # always use generated default profile
        "--profile:build=default",  # always use generated default profile
        "--build=missing",  # incrementally build missing dependencies
        f"--output-folder={CONAN_OUTPUT}",  # install into artifact directory
    ], capture_output=quiet)


def _setuptools_config_settings(config_settings: ConfigSettings) -> SetuptoolsConfigSettings:
    if config_settings is None:
        return None

    normalized: dict[str, SetuptoolsConfigValue] = {}
    for key, value in config_settings.items():
        if not isinstance(key, str):
            raise TypeError(
                "invalid build backend config_settings key type: "
                f"expected 'str', got {type(key).__name__}"
            )
        if isinstance(value, str):
            normalized[key] = value
            continue
        if isinstance(value, Sequence):
            entries: list[str] = []
            for entry in value:
                if not isinstance(entry, str):
                    raise TypeError(
                        "invalid build backend config_settings sequence value for key "
                        f"{repr(key)}: expected 'str', got {type(entry).__name__}"
                    )
                entries.append(entry)
            normalized[key] = entries
            continue
        raise TypeError(
            "invalid build backend config_settings value for key "
            f"{repr(key)}: expected 'str | Sequence[str]', got "
            f"{type(value).__name__}"
        )
    return normalized


def get_requires_for_build_wheel(config_settings: ConfigSettings = None) -> list[str]:
    """Return additional requirements needed to build a wheel.

    Parameters
    ----------
    config_settings : Mapping[str, str | Sequence[str]] | None, optional
        Frontend-provided PEP 517 config settings.

    Returns
    -------
    list[str]
        Build requirements requested by setuptools for wheel builds.

    Raises
    ------
    TypeError
        If `config_settings` contains unsupported key or value types.

    Notes
    -----
    This hook delegates directly to setuptools and does not invoke Conan.
    """
    settings = _setuptools_config_settings(config_settings)
    return setuptools.build_meta.get_requires_for_build_wheel(settings)


def prepare_metadata_for_build_wheel(
    metadata_directory: str,
    config_settings: ConfigSettings = None,
) -> str:
    """Prepare wheel metadata without building a wheel artifact.

    Parameters
    ----------
    metadata_directory : str
        Destination directory where backend metadata should be written.
    config_settings : Mapping[str, str | Sequence[str]] | None, optional
        Frontend-provided PEP 517 config settings.

    Returns
    -------
    str
        The relative path to the generated metadata directory.

    Raises
    ------
    TypeError
        If `config_settings` contains unsupported key or value types.

    Notes
    -----
    This hook delegates directly to setuptools and does not invoke Conan.
    """
    settings = _setuptools_config_settings(config_settings)
    return setuptools.build_meta.prepare_metadata_for_build_wheel(
        metadata_directory,
        settings,
    )


def build_wheel(
    wheel_directory: str,
    config_settings: ConfigSettings = None,
    metadata_directory: str | None = None,
) -> str:
    """Build a wheel artifact for the current project.

    Parameters
    ----------
    wheel_directory : str
        Destination directory for the produced wheel file.
    config_settings : Mapping[str, str | Sequence[str]] | None, optional
        Frontend-provided PEP 517 config settings.
    metadata_directory : str | None, optional
        Optional metadata directory previously returned by
        `prepare_metadata_for_build_wheel`.

    Returns
    -------
    str
        The wheel filename generated by setuptools.

    Raises
    ------
    TypeError
        If `config_settings` contains unsupported key or value types.
    OSError
        If Conan dependency installation fails.

    Notes
    -----
    This hook performs Bertrand's package-manager pre-step by running Conan install
    from synced artifacts, then delegates wheel construction to setuptools.
    """
    settings = _setuptools_config_settings(config_settings)
    _conan_install(quiet=False)
    return setuptools.build_meta.build_wheel(
        wheel_directory,
        settings,
        metadata_directory,
    )


def get_requires_for_build_sdist(config_settings: ConfigSettings = None) -> list[str]:
    """Return additional requirements needed to build an sdist.

    Parameters
    ----------
    config_settings : Mapping[str, str | Sequence[str]] | None, optional
        Frontend-provided PEP 517 config settings.

    Returns
    -------
    list[str]
        Build requirements requested by setuptools for sdist builds.

    Raises
    ------
    TypeError
        If `config_settings` contains unsupported key or value types.

    Notes
    -----
    This hook delegates directly to setuptools and does not invoke Conan.
    """
    settings = _setuptools_config_settings(config_settings)
    return setuptools.build_meta.get_requires_for_build_sdist(settings)


def build_sdist(sdist_directory: str, config_settings: ConfigSettings = None) -> str:
    """Build a source distribution (sdist) for the current project.

    Parameters
    ----------
    sdist_directory : str
        Destination directory for the produced source distribution.
    config_settings : Mapping[str, str | Sequence[str]] | None, optional
        Frontend-provided PEP 517 config settings.

    Returns
    -------
    str
        The sdist filename generated by setuptools.

    Raises
    ------
    TypeError
        If `config_settings` contains unsupported key or value types.

    Notes
    -----
    This hook delegates directly to setuptools and does not invoke Conan.
    """
    settings = _setuptools_config_settings(config_settings)
    return setuptools.build_meta.build_sdist(sdist_directory, settings)


def get_requires_for_build_editable(config_settings: ConfigSettings = None) -> list[str]:
    """Return additional requirements needed to build an editable wheel.

    Parameters
    ----------
    config_settings : Mapping[str, str | Sequence[str]] | None, optional
        Frontend-provided PEP 660 config settings.

    Returns
    -------
    list[str]
        Build requirements requested by setuptools for editable wheel builds.

    Raises
    ------
    TypeError
        If `config_settings` contains unsupported key or value types.

    Notes
    -----
    This hook delegates directly to setuptools and does not invoke Conan.
    """
    settings = _setuptools_config_settings(config_settings)
    return setuptools.build_meta.get_requires_for_build_editable(settings)


def prepare_metadata_for_build_editable(
    metadata_directory: str,
    config_settings: ConfigSettings = None,
) -> str:
    """Prepare editable metadata without building an editable wheel.

    Parameters
    ----------
    metadata_directory : str
        Destination directory where backend metadata should be written.
    config_settings : Mapping[str, str | Sequence[str]] | None, optional
        Frontend-provided PEP 660 config settings.

    Returns
    -------
    str
        The relative path to the generated metadata directory.

    Raises
    ------
    TypeError
        If `config_settings` contains unsupported key or value types.

    Notes
    -----
    This hook delegates directly to setuptools and does not invoke Conan.
    """
    settings = _setuptools_config_settings(config_settings)
    return setuptools.build_meta.prepare_metadata_for_build_editable(
        metadata_directory,
        settings,
    )


def build_editable(
    wheel_directory: str,
    config_settings: ConfigSettings = None,
    metadata_directory: str | None = None,
) -> str:
    """Build an editable wheel artifact for the current project.

    Parameters
    ----------
    wheel_directory : str
        Destination directory for the produced editable wheel file.
    config_settings : Mapping[str, str | Sequence[str]] | None, optional
        Frontend-provided PEP 660 config settings.
    metadata_directory : str | None, optional
        Optional metadata directory previously returned by
        `prepare_metadata_for_build_editable`.

    Returns
    -------
    str
        The editable wheel filename generated by setuptools.

    Raises
    ------
    TypeError
        If `config_settings` contains unsupported key or value types.
    OSError
        If Conan dependency installation fails.

    Notes
    -----
    This hook performs Bertrand's package-manager pre-step by running Conan install
    from synced artifacts, then delegates editable wheel construction to setuptools.
    """
    settings = _setuptools_config_settings(config_settings)
    _conan_install(quiet=False)
    return setuptools.build_meta.build_editable(
        wheel_directory,
        settings,
        metadata_directory,
    )
