[build-system]
requires = ["setuptools", "wheel", "cython >= 3.0.0b1", "numpy"]
build-backend = "setuptools.build_meta:__legacy__"


[project]
name = "pdcast"
version = "0.0.1"
description = "Pandas data types made easy"
readme = "README.rst"
authors = [
    { name="Eric Erkela", email="eerkela42@gmail.com" }
]
license = { file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Cython",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = [
    "pandas",
    "extension",
    "type",
    "conversion",
    "dispatch",
]
dependencies = [
    "numpy",
    "pandas >= 2.0.0",
    "python-dateutil",
    "pytz",
    "regex",
    "tzlocal",
]
requires-python = ">=3.7"


[project.optional-dependencies]
dev = [
    "cython >= 3.0.0b1",
    "cibuildwheel",
    "pyarrow",
    "pytest",
    "sphinx",
    "sphinx_rtd_theme",
]


[project.urls]
"Homepage" = "https://github.com/eerkela/pdcast"
"Issue Tracker" = "https://github.com/eerkela/pdcast/issues"
