[build-system]
requires = ["setuptools", "wheel", "cython >= 3.0.0b1", "numpy"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.setuptools.packages.find]
include = ["pdcast*"]

[project]
name = "pdcast"
version = "0.5.1"
description = "flexible type extensions for pandas"
authors = [
    { name="Eric Erkela", email="eerkela42@gmail.com" }
]
readme = "README.rst"
license = { file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Cython",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
]
keywords = [
    "cython",
    "numba",
    "numpy",
    "pandas",
    "extension",
    "dtype",
    "ExtensionDtype",
    "data type",
    "type",
    "type check",
    "type system",
    "type safety",
    "type inference",
    "dynamic typing",
    "static typing",
    "strong typing",
    "weak typing",
    "cast",
    "conversion",
    "coercion",
    "type cast",
    "type conversion",
    "type coercion",
    "type promotion",
    "astype",
    "compression",
    "dispatch",
    "multiple dispatch",
    "data science",
    "data analysis",
    "data cleaning",
    "data processing",
    "data manipulation",
    "data transformation",
    "data engineering",
    "ETL",
    "vectorization",
    "optimization",
    "performance tuning",
]
dependencies = [
    "numpy",
    "pandas >= 2.0.0",
    "python-dateutil",
    "pytz",
    "regex",
    "tzlocal",
]
requires-python = ">=3.7"

[project.optional-dependencies]
dev = [
    "bumpver",
    "cibuildwheel",
    "mypy",
    "pyarrow",
    "pylint",
    "pytest",
    "sphinx",
    "sphinx_rtd_theme",
    "sphinx-tabs",
    "sphinx-togglebutton",
]

[project.urls]
"Homepage" = "https://github.com/eerkela/pdcast"
# "Documentation" = "<link to readthedocs>"
"Issue Tracker" = "https://github.com/eerkela/pdcast/issues"

[tool.bumpver]
current_version = "0.5.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"pdcast/__init__.py" = ['__version__ = "{version}"']

[tool.cibuildwheel.windows]
before-all = "choco install visualstudio2022buildtools"  # C/C++ build tools

[tool.pylint]
extension-pkg-allow-list = "pdcast"  # load Cython extensions
load-plugins = ["pylint.extensions.docparams"]
accept-no-param-doc = false          # force function parameters to be documented
accept-no-return-doc = false         # force function return values to be documented
accept-no-raise-doc = false          # force exceptions to be documented
accept-no-yields-doc = false         # force generator yields to be documented
output-format = "colorized"
suggestion-mode = true
jobs = 0

[tool.mypy]
allow_untyped_globals = false        # force globals to be typed
disallow_untyped_defs = true         # force function signatures to be typed
disallow_any_generics = true         # force generic containers to be typed
strict_optional = true               # force Nones to be explicitly typed
warn_redundant_casts = true          # warn if typing.cast() is unnecessary
warn_unused_ignores = true           # warn on unnecessary # type: ignore comments
warn_no_return = true                # warn on functions with no return branch
warn_unreachable = true              # warn on unreachable code after type analysis
pretty = true                        # add source context to error messages
color-output = true                  # colorize error messages
error-summary = true                 # print a short summary for each error

[tool.black]
line-length = 88
