[build-system]
requires = ["setuptools", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "pdcast"
version = "0.0.1"
description = "Flexible type extensions for numpy/pandas"
readme = "README.md"
authors = [
    { name="Eric Erkela", email="eerkela42@gmail.com" }
]
license = { file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Cython",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = [
    "pandas",
    "extension",
    "type",
    "conversion",
    "automl",
    "regression",
    "classification"
]
dependencies = [
    "autosklearn",
    "numpy",
    "pandas",
    "psutil",
    "python-dateutil",
    "pytz",
    "regex",
    "sklearn",
    "tzlocal"
]
requires-python = ">=3.7"


[project.urls]
"Homepage" = "https://github.com/eerkela/pdcast"
"Issue Tracker" = "https://github.com/eerkela/pdcast/issues"
