[build-system]
requires = ["setuptools", "wheel", "cython >= 3.0.0b1", "numpy"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.setuptools.packages.find]
include = ["pdcast*"]

[project]
name = "pdcast"
version = "0.7.0"
description = "flexible type extensions for pandas"
readme = "README.rst"
authors = [
    { name="Eric Erkela", email="eerkela42@gmail.com" }
]
license = { file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Cython",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = [
    "numpy",
    "pandas",
    "extension",
    "type",
    "dtype",
    "type check",
    "type system",
    "conversion",
    "compression",
    "dispatch",
]
dependencies = [
    "numpy",
    "pandas >= 2.0.0",
    "python-dateutil",
    "pytz",
    "regex",
    "tzlocal",
]
requires-python = ">=3.7"

[project.optional-dependencies]
dev = [
    "bumpver",
    "cibuildwheel",
    "pyarrow",
    "pytest",
    "sphinx",
    "sphinx_rtd_theme",
    "sphinx-tabs",
    "sphinx-togglebutton",
]

[project.urls]
"Homepage" = "https://github.com/eerkela/pdcast"
# "Documentation" = "<link to readthedocs>"
"Issue Tracker" = "https://github.com/eerkela/pdcast/issues"

[tool.bumpver]
current_version = "0.5.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"pdcast/__init__.py" = ['__version__ = "{version}"']

[tool.cibuildwheel.windows]
before-all = "choco install visualstudio2022buildtools"  # C build tools

