"""Mypy stubs for pdcast/types/integer.pyx"""
from pdcast.types import ScalarType, AbstractType

class IntegerType(AbstractType):
    ...

class NumpyIntegerType(AbstractType):
    ...

class PandasIntegerType(AbstractType):
    ...

class SignedIntegerType(AbstractType):
    ...

class NumpySignedIntegerType(AbstractType):
    ...

class PandasSignedIntegerType(AbstractType):
    ...

class PythonIntegerType(ScalarType):
    ...

class UnsignedIntegerType(AbstractType):
    ...

class NumpyUnsignedIntegerType(AbstractType):
    ...

class PandasUnsignedIntegerType(AbstractType):
    ...

class Int8Type(AbstractType):
    ...

class NumpyInt8Type(ScalarType):
    ...

class PandasInt8Type(ScalarType):
    ...

class Int16Type(AbstractType):
    ...

class NumpyInt16Type(ScalarType):
    ...

class PandasInt16Type(ScalarType):
    ...

class Int32Type(AbstractType):
    ...

class NumpyInt32Type(ScalarType):
    ...

class PandasInt32Type(ScalarType):
    ...

class Int64Type(AbstractType):
    ...

class NumpyInt64Type(ScalarType):
    ...

class PandasInt64Type(ScalarType):
    ...

class UInt8Type(AbstractType):
    ...

class NumpyUInt8Type(ScalarType):
    ...

class PandasUInt8Type(ScalarType):
    ...

class UInt16Type(AbstractType):
    ...

class NumpyUInt16Type(ScalarType):
    ...

class PandasUInt16Type(ScalarType):
    ...

class UInt32Type(AbstractType):
    ...

class NumpyUInt32Type(ScalarType):
    ...

class PandasUInt32Type(ScalarType):
    ...

class UInt64Type(AbstractType):
    ...

class NumpyUInt64Type(ScalarType):
    ...

class PandasUInt64Type(ScalarType):
    ...
