"""Mypy stubs for pdcast/util/structs/priority.pyx
"""
from typing import Hashable, Iterable, NoReturn

from .list import HashedList

class PriorityList(HashedList):
    def index(self, item: Hashable, start: int = ..., stop: int = ...) -> int: ...
    def move_up(self, item: Hashable) -> None: ...
    def mode_down(self, item: Hashable) -> None: ...
    def move(self, item: Hashable, index: int) -> None: ...
    def __setitem__(self, index: int | slice, item: Hashable) -> NoReturn: ...
    def __delitem__(self, index: int | slice) -> NoReturn: ...
    def __iadd__(self, other: Iterable[Hashable]) -> NoReturn: ...
    def __imul__(self, repeat: int) -> NoReturn: ...
