# bertrand-managed: bertrand_git.py
# NOTE: the above marker is used to allow Bertrand to automatically rewrite this file
# in-place when the packaged version is updated, rather than warning in the event of a
# mismatch.  All hooks must have a similar marker.
"""A selection of Git-related utilities for use in the Bertrand CLI and custom Git
hooks.

This file will be automatically copied from the `bertrand` package metadata into the
`.git/hooks/` directory for any repository generated by `bertrand init`, etc.  It is
intended to be imported by custom Git hooks, so that they don't need to re-implement
common Git-related functionality themselves, and can remain standalone from the rest of
the `bertrand` codebase.  This is critical, because importing code from `bertrand`
within a git hook could cause ordinary git operations to fail if `bertrand` is not
installed in the current environment.
"""
from __future__ import annotations

import asyncio
import os
import pwd
import re
import shlex
import shutil
import subprocess
import sys
import uuid
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path, PosixPath
from typing import Literal, TextIO

# pylint: disable=redefined-builtin, broad-exception-caught


#######################
####    GENERAL    ####
#######################


# NOTE: These utilities don't specifically have to do with Git, but are included here
# because they don't have any dependencies, and can be reused by Git hooks to improve
# functionality without breaking isolation.  The same utilities are exported to the
# main CLI, so there's no risk of duplication.


TIMEOUT = 30


# In-container path definitions for metadata and runtime control.
METADATA_DIR: PosixPath = PosixPath(".bertrand")
METADATA_LOCK: PosixPath = METADATA_DIR / ".lock"
METADATA_FILE: PosixPath = METADATA_DIR / "env.json"
METADATA_TMP: PosixPath = METADATA_DIR / "tmp"
WORKTREE_MOUNT: PosixPath = PosixPath("/bertrand")
PROJECT_MOUNT: PosixPath = PosixPath("/.bertrand")
CONTAINER_RUNTIME_MOUNT: PosixPath = PosixPath("/run/bertrand")
CONTAINER_SOCKET: PosixPath = CONTAINER_RUNTIME_MOUNT / "rpc.sock"
CONTAINER_TMP_MOUNT: PosixPath = PosixPath("/tmp/bertrand")


# In-container environment variables for relevant configuration, which are set either
# at build time or upon starting the container context, and used to control the
# behavior of the bertrand CLI both inside and outside the container.
BERTRAND_ENV: str = "BERTRAND"                  # "1" to mark as a Bertrand context
ENV_ID_ENV: str = "BERTRAND_ENV_ID"             # unique Bertrand environment UUID
IMAGE_ID_ENV: str = "BERTRAND_IMAGE_ID"         # unique OCI image ID
CONTAINER_ID_ENV: str = "BERTRAND_CONTAINER_ID" # unique OCI container ID
IMAGE_TAG_ENV: str = "BERTRAND_IMAGE_TAG"       # original tag in build matrix
RPC_SOCKET_ENV: str = "BERTRAND_RPC_SOCKET"     # absolute path to container-side RPC socket
PROJECT_ENV: str = "BERTRAND_PROJECT"           # host path to mounted project root
WORKTREE_ENV: str = "BERTRAND_WORKTREE"         # relative path to mounted worktree
CONTAINER_RUNTIME_ENV: str = "BERTRAND_RUNTIME" # relative path to worktree's artifact directory


# common type aliases for serialization
type Scalar = str | bool | int | float
type JSONValue = None | Scalar | Sequence["JSONValue"] | Mapping[str, "JSONValue"]


def inside_image() -> bool:
    """Check if we're currently running inside a Bertrand image build context
    (Containerfile or Bertrand container instance).

    Returns
    -------
    bool
        True if we're either building an image or running inside a container process.
        False otherwise.

    Notes
    -----
    If this is true and `inside_container()` is false, then it means the CLI was
    invoked from a Containerfile during an image build, which corresponds to
    ahead-of-time (AoT) compilation for statically-typed languages.  The `build`
    command takes advantage of this to differentiate between normal (in-image) and
    editable (in-container) installs, for example.
    """
    return os.environ.get(BERTRAND_ENV, "") == "1"


def inside_container() -> bool:
    """Check if we're currently running inside a Bertrand container instance.

    Returns
    -------
    bool
        True if we're running inside a container process, False otherwise.
    """
    return all(key in os.environ for key in (CONTAINER_ID_ENV, IMAGE_ID_ENV, ENV_ID_ENV))


class CompletedProcess(subprocess.CompletedProcess[str]):
    """A subclass of `subprocess.CompletedProcess` that prints the command and its
    output when converted to a string.
    """
    def __str__(self) -> str:
        out = [
            f"Exit code {self.returncode} from command:\n\n"
            f"    {' '.join(shlex.quote(a) for a in self.args)}"
        ]
        if self.stderr:
            out.append(self.stderr.strip())
        return "\n\n".join(out)


class CommandError(subprocess.CalledProcessError):
    """A subclass of `subprocess.CalledProcessError` that prints the command and its
    output when converted to a string.
    """
    def __str__(self) -> str:
        out = [
            f"Exit code {self.returncode} from command:\n\n"
            f"    {' '.join(shlex.quote(a) for a in self.cmd)}"
        ]
        if self.stderr:
            out.append(self.stderr.strip())
        return "\n\n".join(out)


class TimeoutExpired(subprocess.TimeoutExpired):
    """A subclass of `subprocess.TimeoutExpired` that prints the command and any captured
    output when converted to a string.
    """
    def __str__(self) -> str:
        out = [
            f"Command timed out after {self.timeout} seconds:\n\n"
            f"    {' '.join(shlex.quote(a) for a in self.cmd)}"
        ]
        if self.output:
            out.append(self.output.strip())
        if self.stderr:
            out.append(str(self.stderr.strip()))
        return "\n\n".join(out)


@dataclass(frozen=True)
class User:
    """A simple structure representing a user identity by user ID and group ID.

    Attributes
    ----------
    uid : int
        The numeric user ID.
    gid : int
        The numeric group ID.
    name : str
        The username.
    home : Path
        The path to the user's home directory.
    """
    uid: int = field(init=False)
    gid: int = field(init=False)
    name: str = field(init=False)
    home: Path = field(init=False)

    def __post_init__(self) -> None:
        euid = os.geteuid()
        sudo_uid = os.environ.get("SUDO_UID")
        sudo_user = os.environ.get("SUDO_USER")
        if euid == 0 and sudo_uid:
            object.__setattr__(self, 'uid', int(sudo_uid))
            pw = pwd.getpwuid(self.uid)
            object.__setattr__(self, 'gid', pw.pw_gid)
            object.__setattr__(self, 'name', sudo_user or pw.pw_name)
            object.__setattr__(self, 'home', Path(pw.pw_dir))
        else:
            object.__setattr__(self, 'uid', os.getuid())
            pw = pwd.getpwuid(self.uid)
            object.__setattr__(self, 'gid', pw.pw_gid)
            object.__setattr__(self, 'name', pw.pw_name)
            object.__setattr__(self, 'home', Path(pw.pw_dir))


def atomic_write_text(
    path: Path,
    text: str,
    encoding: str | None = None,
    private: bool = False,
) -> None:
    """Atomically write text to a file, avoiding race conditions and partial writes.

    Parameters
    ----------
    path : Path
        The path to write to.
    text : str
        The text to write.
    encoding : str | None, optional
        The text encoding to use (default is None, which uses the system default).
    private : bool, optional
        Whether to set private permissions (0600) on the written file, by default False.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.tmp.{uuid.uuid4().hex}")
    tmp.write_text(text, encoding=encoding)
    try:
        with tmp.open("r+", encoding=encoding) as f:
            f.flush()
            os.fsync(f.fileno())
    except OSError:
        pass
    if private:
        try:
            tmp.chmod(0o600)
        except OSError:
            pass
    tmp.replace(path)


def atomic_write_bytes(path: Path, data: bytes, private: bool = False) -> None:
    """Atomically write bytes to a file, avoiding race conditions and partial writes.

    Parameters
    ----------
    path : Path
        The path to write to.
    data : bytes
        The bytes to write.
    private : bool, optional
        Whether to set private permissions (0600) on the written file, by default False.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.tmp.{uuid.uuid4().hex}")
    tmp.write_bytes(data)
    try:
        with tmp.open("r+b") as f:
            f.flush()
            os.fsync(f.fileno())
    except OSError:
        pass
    if private:
        try:
            tmp.chmod(0o600)
        except OSError:
            pass
    tmp.replace(path)


def can_escalate() -> bool:
    """
    Returns
    -------
    bool
        True if privilege escalation is possible on the current system, false
        otherwise.
    """
    return os.name == "posix" and bool(shutil.which("sudo") or shutil.which("doas"))


def confirm(prompt: str, *, assume_yes: bool = False) -> bool:
    """Ask the user for a yes/no confirmation for a given prompt.

    Parameters
    ----------
    prompt : str
        The prompt to display to the user.
    assume_yes : bool, optional
        If True, automatically return True without prompting the user.  Default is
        False.

    Returns
    -------
    bool
        True if the user confirmed yes, false otherwise.
    """
    if assume_yes:
        return True
    try:
        response = input(prompt).strip().lower()
    except EOFError:
        return False
    return response in {"y", "yes"}


def mkdir_private(path: Path) -> None:
    """Create a directory with private permissions (0700) if it does not already exist.

    Parameters
    ----------
    path : Path
        The path to create.
    """
    path.mkdir(parents=True, exist_ok=True)
    try:
        path.chmod(0o700)
    except OSError:
        pass


async def _run_no_capture(
    argv: list[str],
    proc: asyncio.subprocess.Process,
    timeout: float | None,
    input: str | None,
) -> CompletedProcess | CommandError | None:
    input_bytes = None if input is None else input.encode(
        "utf-8",
        errors="replace"
    )
    try:
        await asyncio.wait_for(
            proc.communicate(input_bytes),
            timeout=timeout
        )
    except TimeoutError as err:
        proc.kill()
        await proc.communicate()
        raise TimeoutExpired(
            cmd=argv,
            timeout=timeout or 0.0,
            output=None,
            stderr=None
        ) from err

    if proc.returncode is None:
        proc.kill()
        await proc.wait()
        return None

    if proc.returncode == 0:
        return CompletedProcess(argv, proc.returncode, "", "")
    return CommandError(proc.returncode, argv, "", "")


async def _run_capture(
    argv: list[str],
    proc: asyncio.subprocess.Process,
    timeout: float | None,
    input: str | None,
) -> CompletedProcess | CommandError | None:
    input_bytes = None if input is None else input.encode(
        "utf-8",
        errors="replace"
    )
    try:
        stdout_raw, stderr_raw = await asyncio.wait_for(
            proc.communicate(input_bytes),
            timeout=timeout,
        )
    except TimeoutError as err:
        proc.kill()
        stdout_raw, stderr_raw = await proc.communicate()
        raise TimeoutExpired(
            cmd=argv,
            timeout=timeout or 0.0,
            output=stdout_raw.decode("utf-8", errors="replace") or None,
            stderr=stderr_raw.decode("utf-8", errors="replace") or None,
        ) from err

    if proc.returncode is None:
        proc.kill()
        await proc.wait()
        return None

    stdout_text = stdout_raw.decode("utf-8", errors="replace")
    stderr_text = stderr_raw.decode("utf-8", errors="replace")
    if proc.returncode == 0:
        return CompletedProcess(
            argv,
            proc.returncode,
            stdout_text,
            stderr_text
        )
    return CommandError(
        proc.returncode,
        argv,
        stdout_text,
        stderr_text
    )


async def _tee(src: asyncio.StreamReader | None, sink: TextIO, buf_list: list[str]) -> None:
    if src is None:
        return
    while True:
        chunk = await src.readline()
        if not chunk:
            break
        text = chunk.decode("utf-8", errors="replace")
        buf_list.append(text)
        try:
            sink.write(text)
            sink.flush()
        except OSError:
            pass


async def _write_stdin(dst: asyncio.StreamWriter | None, data: str) -> None:
    if dst is None:
        return
    try:
        dst.write(data.encode("utf-8", errors="replace"))
        await dst.drain()
    except (BrokenPipeError, ConnectionResetError, OSError):
        pass
    finally:
        try:
            dst.close()
            await dst.wait_closed()
        except (AttributeError, RuntimeError, OSError):
            pass


async def _run_tee(
    argv: list[str],
    proc: asyncio.subprocess.Process,
    timeout: float | None,
    input: str | None,
) -> CompletedProcess | CommandError | None:
    stdout_lines: list[str] = []
    stderr_lines: list[str] = []
    tasks: list[asyncio.Task[None]] = [
        asyncio.create_task(_tee(
            proc.stdout,
            sys.stdout,
            stdout_lines
        )),
        asyncio.create_task(_tee(
            proc.stderr,
            sys.stderr,
            stderr_lines
        )),
    ]
    if input is not None:
        tasks.append(asyncio.create_task(_write_stdin(proc.stdin, input)))

    try:
        try:
            await asyncio.wait_for(proc.wait(), timeout=timeout)
        except TimeoutError as err:
            proc.kill()
            await proc.wait()
            for task in tasks:
                await task
            stdout_text = "".join(stdout_lines)
            stderr_text = "".join(stderr_lines)
            raise TimeoutExpired(
                cmd=argv,
                timeout=timeout or 0.0,
                output=stdout_text or None,
                stderr=stderr_text or None,
            ) from err
    finally:
        for task in tasks:
            await task

    if proc.returncode is None:
        proc.kill()
        await proc.wait()
        return None

    stdout_text = "".join(stdout_lines)
    stderr_text = "".join(stderr_lines)
    if proc.returncode == 0:
        return CompletedProcess(
            argv,
            proc.returncode,
            stdout_text,
            stderr_text
        )
    return CommandError(proc.returncode, argv, stdout_text, stderr_text)


async def run(
    argv: list[str],
    *,
    check: bool = True,
    capture_output: bool | None = False,
    input: str | None = None,
    timeout: float | None = None,
    attempts: int = 1,
    delay: float = 0.1,    
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> CompletedProcess:
    """An asynchronous subprocess wrapper that defaults to text mode and properly
    formats errors.

    Parameters
    ----------
    argv : list[str]
        The command and its arguments to run.
    check : bool, optional
        Whether to raise a `CommandError` if the command fails (default is True).  If
        false, then any errors will be ignored.
    capture_output : bool | None, optional
        If true, then all output will be redirected to the returned `CompletedProcess`
        or `CommandError`, and excluded from the inherited stdout/stderr streams.  If
        false (the default), then the opposite is the case, and the returned
        `CompletedProcess` or `CommandError` will not include any captured output.  If
        None, then output will be "tee'd" to both the console and the returned objects
        simultaneously.  Note that teeing output in this way may break TTY behavior for
        some commands, and is not recommended for interactive use.
    input : str | None, optional
        Input to send to the command's stdin (default is None).
    timeout : float | None, optional
        An optional timeout in seconds to wait for the command to complete before
        raising a `TimeoutExpired` exception.  Default is None, which means to wait
        indefinitely.  If zero or negative, a `TimeoutExpired` exception will be raised
        immediately.  Note that this does not reset between `attempts`, so the total
        time spent on retries counts against the timeout.
    attempts : int, optional
        The total number of times to attempt the command.  Defaults to 1, which means
        no retries.  If greater than 1, then any command that exits with a nonzero
        exit code will be re-run after a short delay, up to the specified number
        of times in total.
    delay : float, optional
        The delay in seconds to wait between retries when `attempts` is greater than 1.
        Default is 0.1 seconds.  Must be non-negative.
    cwd : Path | None, optional
        An optional working directory to run the command in.  If None (the default),
        then the current working directory will be used.
    env : Mapping[str, str] | None, optional
        An optional environment dictionary to use for the command.  If None (the
        default), then the current process's environment will be used.

    Returns
    -------
    CompletedProcess
        The completed process result.

    Raises
    ------
    CommandError
        If the command fails and `check` is True.  If `attempts > 1`, then this will
        only reflect the last attempt, and any previous errors will be ignored.
    TimeoutExpired
        If the command does not complete within the specified timeout.
    OSError
        If we failed to open the subprocess or its output streams.
    """
    if attempts < 1:
        raise ValueError("attempts must be at least 1")
    if delay < 0:
        raise ValueError("delay must be non-negative")

    # get overall deadline across attempts
    deadline: float | None
    if timeout is None:
        deadline = None
    elif timeout <= 0.0:
        raise TimeoutExpired(cmd=argv, timeout=timeout, output=None, stderr=None)
    else:
        deadline = asyncio.get_event_loop().time() + timeout

    # loop until success, deadline is exceeded, or attempts are exhausted
    last_error: CommandError | None = None
    while attempts > 0:
        result: CompletedProcess | CommandError | None = None
        proc = await asyncio.create_subprocess_exec(
            *argv,
            stdin=asyncio.subprocess.PIPE if input is not None else None,
            stdout=None if capture_output is False else asyncio.subprocess.PIPE,
            stderr=None if capture_output is False else asyncio.subprocess.PIPE,
            cwd=cwd,
            env=env,
        )
        if deadline is not None:
            timeout = deadline - asyncio.get_event_loop().time()

        # capture_output=False -> inherit terminal streams and do not capture output
        if capture_output is False:
            result = await _run_no_capture(
                argv,
                proc,
                timeout,
                input
            )

        # capture_output=True -> full capture with no tee
        elif capture_output is True:
            result = await _run_capture(
                argv,
                proc,
                timeout,
                input
            )

        # capture_output=None -> tee streams while capturing for return/errors
        else:
            result = await _run_tee(
                argv,
                proc,
                timeout,
                input
            )

        if isinstance(result, CompletedProcess):
            return result
        last_error = result
        attempts -= 1
        if attempts > 0:
            await asyncio.sleep(delay)

    # exhausted all attempts
    if last_error is not None:
        if check:
            raise last_error
        return CompletedProcess(
            argv,
            last_error.returncode,
            last_error.output or "",
            last_error.stderr or ""
        )
    err = (
        "unspecified error: command did not complete successfully, but no error "
        "information was captured"
    )
    if check:
        raise CommandError(-1, argv, None, err)
    return CompletedProcess(argv, -1, "", err)


# TODO: I should probably just remove `sanitize_name()` to be honest, and do the
# regex logic inline, since the set of allowable characters changes depending on the
# context.


SANITIZE = re.compile(r"[^a-zA-Z0-9._]+")


def sanitize_name(name: str, *, replace: str = "_") -> str:
    """Replace any characters in the given name that are not alphanumeric, '.', or '_'
    with the specified replacement character, and then strip leading and trailing
    replacement characters from the result.

    Parameters
    ----------
    name : str
        The name to sanitize.
    replace : str, optional
        The character to use as a replacement for invalid characters.  Default is '_'.

    Returns
    -------
    str
        The sanitized name.
    """
    return SANITIZE.sub(replace, name).strip(replace)


def sudo(argv: list[str], *, non_interactive: bool = False) -> list[str]:
    """Return a command with privilege escalation prepended when needed.

    Parameters
    ----------
    argv : list[str]
        The command and its arguments.
    non_interactive : bool, optional
        If True, add non-interactive flags for the selected escalator so it fails
        immediately instead of prompting for a password.

    Returns
    -------
    list[str]
        A new list containing either the original command (when no escalation is
        needed/available) or the escalated command.

    Notes
    -----
    Escalation is only attempted on POSIX systems for non-root users.  The selection
    order is `sudo`, then `doas`.
    """
    # no-op outside POSIX, when already root, or when no supported escalator is found
    if os.name != "posix" or os.geteuid() == 0:
        return argv.copy()
    escalator = None
    if shutil.which("sudo"):
        escalator = "sudo"
    elif shutil.which("doas"):
        escalator = "doas"
    if escalator is None:
        return argv.copy()

    out = [escalator]
    if non_interactive:
        out.append("-n")
    out.extend(argv)
    return out


####################
####    KUBE    ####
####################


# Kubernetes engine/`containerd` CLI config.
MICROK8S_CHANNEL = "1.33/stable"
MICROK8S_GROUP = "microk8s"
MICROK8S_CONTAINERD_SOCKET = Path("/var/snap/microk8s/common/run/containerd.sock")
MICROK8S_CONTAINERD_ADDRESS = f"unix://{MICROK8S_CONTAINERD_SOCKET.as_posix()}"
NERDCTL_VERSION = "2.2.2"
NERDCTL_NAMESPACE = "bertrand"
NERDCTL_BASE_URL = (
    f"https://github.com/containerd/nerdctl/releases/download/v{NERDCTL_VERSION}"
)
NERDCTL_CHECKSUM: dict[str, str] = {  # checksums for nerdctl download
    "amd64": "8a477f35533c6cc1120c19558d8142967c74f25a4b952b481f48104e030de914",
    "arm64": "55d68d2613b5f065021146bac21f620cde9e7fdd4bd3eff74cd324f5462e107a",
}


# Host paths for Bertrand's MicroK8s cluster and related tools
STATE_DIR = User().home / ".local" / "share" / "bertrand"
TOOLS_DIR = STATE_DIR / "tools"
TOOLS_BIN_DIR = STATE_DIR / "bin"
TOOLS_RUN_DIR = STATE_DIR / "run"
TOOLS_TMP_DIR = STATE_DIR / "tmp"
NERDCTL_INSTALL_DIR = TOOLS_DIR / f"nerdctl-{NERDCTL_VERSION}"
NERDCTL_BIN = NERDCTL_INSTALL_DIR / "bin" / "nerdctl"
BUILDCTL_BIN = NERDCTL_INSTALL_DIR / "bin" / "buildctl"
BUILDKITD_BIN: Path = NERDCTL_INSTALL_DIR / "bin" / "buildkitd"
BUILDKIT_SOCKET = TOOLS_RUN_DIR / "buildkitd.sock"
BUILDKIT_ADDRESS = f"unix://{BUILDKIT_SOCKET.as_posix()}"
BUILDKIT_PID_FILE = TOOLS_RUN_DIR / "buildkitd.pid"
BUILDKIT_LOG_FILE = TOOLS_RUN_DIR / "buildkitd.log"
BUILDKIT_LOCK_FILE = TOOLS_RUN_DIR / "buildkitd.lock"


type ContainerState = Literal[
    "created",
    "restarting",
    "running",
    "removing",
    "paused",
    "exited",
    "dead"
]


async def nerdctl(
    argv: list[str],
    *,
    check: bool = True,
    capture_output: bool | None = False,
    input: str | None = None,
    timeout: float | None = None,
    attempts: int = 1,
    delay: float = 0.1,
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> CompletedProcess:
    """Invoke the managed nerdctl binary against Bertrand's MicroK8s containerd.

    Parameters
    ----------
    argv : list[str]
        The `nerdctl` subcommand to run, plus arguments, minus the `nerdctl` binary
        itself.  The command will always target the MicroK8s containerd instance.
    check : bool, optional
        Whether to raise a `CommandError` if the command fails (default is True).  If
        false, then any errors will be ignored.
    capture_output : bool | None, optional
        If true, then all output will be redirected to the returned `CompletedProcess`
        or `CommandError`, and excluded from the inherited stdout/stderr streams.  If
        false (the default), then the opposite is the case, and the returned
        `CompletedProcess` or `CommandError` will not include any captured output.  If
        None, then output will be "tee'd" to both the console and the returned objects
        simultaneously.  Note that teeing output in this way may break TTY behavior for
        some commands, and is not recommended for interactive use.
    input : str | None, optional
        Input to send to the command's stdin (default is None).
    timeout : float | None, optional
        An optional timeout in seconds to wait for the command to complete before
        raising a `TimeoutExpired` exception.  Default is None, which means to wait
        indefinitely.  If zero or negative, a `TimeoutExpired` exception will be raised
        immediately.  Note that this does not reset between `attempts`, so the total
        time spent on retries counts against the timeout.
    attempts : int, optional
        The total number of times to attempt the command.  Defaults to 1, which means
        no retries.  If greater than 1, then any command that exits with a nonzero
        exit code will be re-run after a short delay, up to the specified number
        of times in total.
    delay : float, optional
        The delay in seconds to wait between retries when `attempts` is greater than 1.
        Default is 0.1 seconds.  Must be non-negative.
    cwd : Path | None, optional
        An optional working directory to run the command in.  If None (the default),
        then the current working directory will be used.
    env : Mapping[str, str] | None, optional
        An optional environment dictionary to use for the command.  If None (the
        default), then the current process's environment will be used.

    Returns
    -------
    CompletedProcess
        The completed process result.

    Raises
    ------
    CommandError
        If the command fails and `check` is True.
    TimeoutExpired
        If the command does not complete within the specified timeout.
    OSError
        If we failed to open the subprocess or its output streams.
    """
    cmd = [
        str(NERDCTL_BIN),
        "--address", MICROK8S_CONTAINERD_ADDRESS,
        "--namespace", NERDCTL_NAMESPACE,
        *argv,
    ]
    merged_env = os.environ.copy()
    if env is not None:
        merged_env.update(env)
    merged_env["BUILDKIT_HOST"] = BUILDKIT_ADDRESS
    return await run(
        cmd,
        check=check,
        capture_output=capture_output,
        input=input,
        timeout=timeout,
        attempts=attempts,
        delay=delay,
        cwd=cwd,
        env=merged_env,
    )


async def nerdctl_ids(
    mode: Literal["container", "image", "volume", "network", "secret"],
    labels: Mapping[str, str],
    *,
    status: Sequence[ContainerState] | None = None,
    timeout: float = TIMEOUT,
) -> list[str]:
    """Retrieve a list of nerdctl container/image/volume IDs that match the given
    labels and status filters, if applicable.

    Parameters
    ----------
    mode : Literal["container", "image", "volume", "network", "secret"]
        The type of nerdctl objects to query for.
    labels : Mapping[str, str]
        A mapping of label keys and values to filter the results by.  Only objects that
        have all of the specified labels with matching values will be included in the
        results.
    status : Sequence[ContainerState] | None, optional
        An optional sequence of container statuses to filter by when `mode` is
        "container".  If None (the default), then containers of all statuses will be
        included in the results.
    timeout : float, optional
        The maximum time in seconds to wait for the nerdctl command to complete before
        raising a `TimeoutExpired` exception.

    Returns
    -------
    list[str]
        A list of nerdctl container/image/volume IDs that match the specified filters.

    Raises
    ------
    ValueError
        If `mode` is not one of the allowed literals.
    TimeoutError
        If the nerdctl command does not complete within the specified timeout.
    TimeoutExpired
        If the nerdctl command does not complete within the specified timeout.
    CommandError
        If the nerdctl command fails for any reason other than a timeout.
    KeyboardInterrupt
        If the operation is interrupted by the user.
    SystemExit
        If some other fatal error is encountered.
    """
    loop = asyncio.get_event_loop()
    deadline = loop.time() + timeout

    # form basic command based on mode
    cmd: list[str] = []
    if mode == "container":
        cmd.extend([
            "container",
            "ls",
            "-a",
            "-q",
            "--no-trunc",
            "--filter", f"label={BERTRAND_ENV}=1"
        ])
    elif mode == "image":
        cmd.extend([
            "image",
            "ls",
            "-a",
            "-q",
            "--no-trunc",
            "--filter", f"label={BERTRAND_ENV}=1"
        ])
    elif mode == "volume":
        cmd.extend(["volume", "ls", "-q", "--filter", f"label={BERTRAND_ENV}=1"])
    elif mode == "network":
        cmd.extend(["network", "ls", "-q", "--filter", f"label={BERTRAND_ENV}=1"])
    elif mode == "secret":
        cmd.extend(["secret", "ls", "-q", "--filter", f"label={BERTRAND_ENV}=1"])
    else:
        raise ValueError(f"invalid mode: {mode}")

    # append additional labels to filter results
    for k, v in labels.items():
        cmd.extend(["--filter", f"label={k}={v}"])

    # parse results, returning an empty/partial list on failure (best-effort)
    out: list[str] = []
    seen: set[str] = set()
    try:
        # return all statuses by default
        if status is None:
            result = await nerdctl(
                cmd,
                capture_output=True,
                check=False,
                timeout=deadline - loop.time()
            )
            if result.returncode == 0:
                for raw_id in result.stdout.splitlines():
                    container_id = raw_id.strip()
                    if not container_id or container_id in seen:
                        continue
                    seen.add(container_id)
                    out.append(container_id)
            return out

        # filter by status
        for stat in status:
            result = await nerdctl(
                [*cmd, "--filter", f"status={stat}"],
                capture_output=True,
                check=False,
                timeout=deadline - loop.time()
            )
            if result.returncode != 0:
                continue
            for raw_id in result.stdout.splitlines():
                container_id = raw_id.strip()
                if not container_id or container_id in seen:
                    continue
                seen.add(container_id)
                out.append(container_id)
    except (TimeoutError, TimeoutExpired, KeyboardInterrupt, SystemExit):
        raise
    except Exception:
        pass
    return out


async def buildctl(
    argv: list[str],
    *,
    check: bool = True,
    capture_output: bool | None = False,
    input: str | None = None,
    timeout: float | None = None,
    attempts: int = 1,
    delay: float = 0.1,
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> CompletedProcess:
    """Invoke the managed buildctl binary against Bertrand's BuildKit daemon.

    Parameters
    ----------
    argv : list[str]
        The `buildctl` subcommand to run, plus arguments, minus the `buildctl` binary
        itself.  The command will always target Bertrand's pinned BuildKit daemon,
        which must be started separately via the `ensure_buildkit()` helper before
        calling this function.
    check : bool, optional
        Whether to raise a `CommandError` if the command fails (default is True).  If
        false, then any errors will be ignored.
    capture_output : bool | None, optional
        If true, then all output will be redirected to the returned `CompletedProcess`
        or `CommandError`, and excluded from the inherited stdout/stderr streams.  If
        false (the default), then the opposite is the case, and the returned
        `CompletedProcess` or `CommandError` will not include any captured output.  If
        None, then output will be "tee'd" to both the console and the returned objects
        simultaneously.  Note that teeing output in this way may break TTY behavior for
        some commands, and is not recommended for interactive use.
    input : str | None, optional
        Input to send to the command's stdin (default is None).
    timeout : float | None, optional
        An optional timeout in seconds to wait for the command to complete before
        raising a `TimeoutExpired` exception.  Default is None, which means to wait
        indefinitely.  If zero or negative, a `TimeoutExpired` exception will be raised
        immediately.  Note that this does not reset between `attempts`, so the total
        time spent on retries counts against the timeout.
    attempts : int, optional
        The total number of times to attempt the command.  Defaults to 1, which means
        no retries.  If greater than 1, then any command that exits with a nonzero
        exit code will be re-run after a short delay, up to the specified number
        of times in total.
    delay : float, optional
        The delay in seconds to wait between retries when `attempts` is greater than 1.
        Default is 0.1 seconds.  Must be non-negative.
    cwd : Path | None, optional
        An optional working directory to run the command in.  If None (the default),
        then the current working directory will be used.
    env : Mapping[str, str] | None, optional
        An optional environment dictionary to use for the command.  If None (the
        default), then the current process's environment will be used.

    Returns
    -------
    CompletedProcess
        The completed process result.

    Raises
    ------
    CommandError
        If the command fails and `check` is True.
    TimeoutExpired
        If the command does not complete within the specified timeout.
    OSError
        If we failed to open the subprocess or its output streams.
    """
    cmd = [
        str(BUILDCTL_BIN),
        "--addr",
        BUILDKIT_ADDRESS,
        *argv,
    ]
    return await run(
        cmd,
        check=check,
        capture_output=capture_output,
        input=input,
        timeout=timeout,
        attempts=attempts,
        delay=delay,
        cwd=cwd,
        env=env,
    )


async def kubectl(
    argv: list[str],
    *,
    check: bool = True,
    capture_output: bool | None = False,
    input: str | None = None,
    timeout: float | None = None,
    attempts: int = 1,
    delay: float = 0.1,
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> CompletedProcess:
    """Invoke the `microk8s kubectl` command against the local MicroK8s cluster.

    Parameters
    ----------
    argv : list[str]
        The `kubectl` subcommand to run, plus arguments, minus the `microk8s kubectl`
        prefix itself.  The command requires that the MicroK8s cluster is up and
        running locally.
    check : bool, optional
        Whether to raise a `CommandError` if the command fails (default is True).  If
        false, then any errors will be ignored.
    capture_output : bool | None, optional
        If true, then all output will be redirected to the returned `CompletedProcess`
        or `CommandError`, and excluded from the inherited stdout/stderr streams.  If
        false (the default), then the opposite is the case, and the returned
        `CompletedProcess` or `CommandError` will not include any captured output.  If
        None, then output will be "tee'd" to both the console and the returned objects
        simultaneously.  Note that teeing output in this way may break TTY behavior for
        some commands, and is not recommended for interactive use.
    input : str | None, optional
        Input to send to the command's stdin (default is None).
    timeout : float | None, optional
        An optional timeout in seconds to wait for the command to complete before
        raising a `TimeoutExpired` exception.  Default is None, which means to wait
        indefinitely.  If zero or negative, a `TimeoutExpired` exception will be raised
        immediately.  Note that this does not reset between `attempts`, so the total
        time spent on retries counts against the timeout.
    attempts : int, optional
        The total number of times to attempt the command.  Defaults to 1, which means
        no retries.  If greater than 1, then any command that exits with a nonzero
        exit code will be re-run after a short delay, up to the specified number
        of times in total.
    delay : float, optional
        The delay in seconds to wait between retries when `attempts` is greater than 1.
        Default is 0.1 seconds.  Must be non-negative.
    cwd : Path | None, optional
        An optional working directory to run the command in.  If None (the default),
        then the current working directory will be used.
    env : Mapping[str, str] | None, optional
        An optional environment dictionary to use for the command.  If None (the
        default), then the current process's environment will be used.

    Returns
    -------
    CompletedProcess
        The completed process result.

    Raises
    ------
    CommandError
        If the command fails and `check` is True.
    TimeoutExpired
        If the command does not complete within the specified timeout.
    OSError
        If we failed to open the subprocess or its output streams.
    """
    cmd = ["microk8s", "kubectl"]
    cmd.extend(argv)
    return await run(
        cmd,
        check=check,
        capture_output=capture_output,
        input=input,
        timeout=timeout,
        attempts=attempts,
        delay=delay,
        cwd=cwd,
        env=env,
    )


###################
####    GIT    ####
###################


# NOTE: These utilities are intended to be imported by Git hooks via
# `from bertrand_git import ...` (notice no relative paths/leading dot).  The
# `bertrand init` command ensures that this file is copied into the `.git/hooks/`
# directory alongside the hooks themselves, so that the import will always resolve
# properly.  Note that it IS NOT SAFE to import code from third-party libraries or
# across hooks, since the hook names may be rewritten in order to conform to Git's
# expectations.  This is the ONLY file that Bertrand guarantees to be importable from
# downstream hooks.


type GitRefState = Literal["prepared", "committed", "aborted"]


GIT_REF_HEADS_PREFIX = "refs/heads/"
GIT_REF_STATES: frozenset[GitRefState] = frozenset({"prepared", "committed", "aborted"})
GIT_REQUIRE_RELATIVE_PATHS = (
    "git worktree relative path support is required for bare repository mode, but "
    "this git version does not support '--relative-paths' for worktree creation and "
    "move operations.  Please upgrade git to a version that supports this feature "
    "(git 2.52+)."
)


@dataclass(frozen=True)
class GitRefUpdate:
    """A single reference update received from git on stdin."""
    old: str
    new: str
    ref: str

    @property
    def is_head(self) -> bool:
        """
        Returns
        -------
        bool
            True if this update targets `refs/heads/*`.
        """
        return self.ref.startswith(GIT_REF_HEADS_PREFIX)

    @property
    def branch(self) -> str:
        """
        Returns
        -------
        str
            The short branch name for `refs/heads/*` updates.
        """
        return self.ref[len(GIT_REF_HEADS_PREFIX):]

    @property
    def created(self) -> bool:
        """
        Returns
        -------
        bool
            True if this update created a new ref.
        """
        return all(c == "0" for c in self.old) and any(c != "0" for c in self.new)

    @property
    def destroyed(self) -> bool:
        """
        Returns
        -------
        bool
            True if this update deleted an existing ref.
        """
        return any(c != "0" for c in self.old) and all(c == "0" for c in self.new)

    @classmethod
    def parse(cls, stdin: str) -> list[GitRefUpdate]:
        """Parse and validate transaction update lines from stdin.

        Parameters
        ----------
        stdin : str
            The raw stdin input containing reference update lines, typically read from
            the `reference-transaction` hook's standard input stream.

        Returns
        -------
        list[GitRefUpdate]
            A list of parsed reference updates.

        Raises
        ------
        ValueError
            If any line is malformed.
        """
        updates: list[GitRefUpdate] = []
        for index, raw in enumerate(stdin.splitlines(), start=1):
            line = raw.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) != 3:
                raise ValueError(
                    f"malformed git transaction line {index}: expected "
                    f"'<old> <new> <ref>', got: {raw!r}"
                )
            old, new, ref = (part.strip() for part in parts)
            if not ref:
                raise ValueError(
                    f"malformed git transaction line {index}: ref must not be empty"
                )
            updates.append(cls(old=old, new=new, ref=ref))
        return updates


@dataclass(frozen=True)
class GitRepository:
    """An object-oriented wrapper around a git repository, which simplifies access to
    its branches, worktrees, and other properties.

    Attributes
    ----------
    git_dir : Path, optional
        The path to the repository's .git directory.  If omitted, the repository will
        be by running `git rev-parse --git-common-dir` in the current working
        directory.
    """
    @dataclass(frozen=True)
    class Worktree:
        """A parsed entry from `git worktree list --porcelain`.

        Attributes
        ----------
        path : Path
            The absolute path to the worktree checkout.
        branch : str | None
            The short branch name if this worktree is attached to `refs/heads/*`,
            otherwise None.
        """
        path: Path
        branch: str | None = None

        def __post_init__(self) -> None:
            object.__setattr__(self, "path", self.path.expanduser().resolve())
            if not self.path.exists():
                raise FileNotFoundError(f"worktree path does not exist: {self.path}")
            if not self.path.is_dir():
                raise NotADirectoryError(f"invalid worktree path: {self.path}")

    git_dir: Path

    @property
    def root(self) -> Path:
        """
        Returns
        -------
        Path
            The absolute path to the repository's root directory, which is the parent of
            the .git directory.
        """
        return self.git_dir.parent

    def __post_init__(self) -> None:
        object.__setattr__(self, "git_dir", self.git_dir.expanduser().resolve())

    @classmethod
    async def discover(cls, path: Path | None = None) -> GitRepository | None:
        """Discover the Git repository for the current working directory.

        Parameters
        ----------
        path : Path | None, optional
            An optional path to use as the starting point for discovery.  If None (the
            default), then the current working directory will be used.

        Returns
        -------
        GitRepository | None
            The discovered Git repository, assuming a `path` is inside a Git repository

        Raises
        ------
        CommandError
            If the git command fails, which may indicate that the current directory is
            not within a Git repository.
        """
        result = await run(
            ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
            cwd=path,
            check=False,
            capture_output=True
        )
        if result.returncode == 0:
            return cls(git_dir=Path(result.stdout.strip()))
        return None

    @classmethod
    async def resolve(cls, path: Path) -> tuple[GitRepository, Path]:
        """Given a path, resolve an ancestor git repository and compute the
        corresponding worktree path within it.

        Parameters
        ----------
        path : Path
            The input path to resolve a repository and worktree for.  The ancestors
            will be scanned to find the nearest git repository, and the remaining path
            components will be treated as a relative worktree path within the
            repository.  If no repository is found, then the input path will be
            treated as an uninitialized repository, and the worktree will reflect the
            Git installation's default branch (e.g. "master" or "main").  If the
            path leads to a bare repository, then the worktree will resolve to its
            attached HEAD worktree, if it has one.

        Returns
        -------
        tuple[GitRepository, Path]
            A tuple containing the resolved Git repository and the relative worktree
            path within it, accounting for HEAD extensions and nested bare/non-bare
            worktree layouts.  Note that the `GitRepository` may be uninitialized if
            no existing repository was found during resolution.

        Raises
        ------
        OSError
            If the resolved repository is bare and does not support relative paths,
            the resolved worktree is not contained within the repository, or if the
            path leads to a bare repository with a detached HEAD.
        """
        repo = await cls.discover(path)

        # new bare repository
        if repo is None:
            if not await cls.supports_relative_paths():
                raise OSError(GIT_REQUIRE_RELATIVE_PATHS)
            repo = cls(path / ".git")
            return repo, Path(await cls.default_branch())

        # existing bare repository
        if await repo.is_bare():
            if not await cls.supports_relative_paths():
                raise OSError(GIT_REQUIRE_RELATIVE_PATHS)
            worktree = path.relative_to(repo.root)
            if not worktree.parts:  # extend to HEAD worktree
                head = await repo.head_branch()
                if head is None:
                    raise OSError(
                        f"cannot target a bare repository with a detached HEAD: {path}"
                    )
                await repo.sync_worktrees()
                candidate = next(
                    (wt.path for wt in await repo.worktrees() if wt.branch == head),
                    None
                )
                if candidate is None:
                    raise OSError(
                        f"HEAD branch '{head}' is not checked out in any worktree of "
                        f"repository: {path}"
                    )
                if not candidate.is_relative_to(path):
                    raise OSError(
                        f"resolved worktree path '{candidate}' is not contained within "
                        f"repository: {path}"
                    )
                worktree = candidate.relative_to(path)
            elif not any(wt.path == path for wt in await repo.worktrees()):
                raise OSError(
                    f"worktree at {worktree} is not registered as a git worktree of "
                    f"bare repository: {repo.root}"
                )
            return repo, worktree

        # existing non-bare repository
        worktree = path.relative_to(repo.root)
        if worktree.parts and not any(wt.path == path for wt in await repo.worktrees()):
            raise OSError(
                f"nested worktree at {worktree} is not registered as a git worktree "
                f"of non-bare repository: {repo.root}"
            )
        return repo, worktree

    def __bool__(self) -> bool:
        return (
            self.git_dir.exists() and
            self.git_dir.is_dir() and
            subprocess.run(
                ["git", "--git-dir", str(self.git_dir), "rev-parse", "--git-dir"],
                check=False,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            ).returncode == 0
        )

    async def init(self, *, branch: str | None = None, bare: bool = True) -> None:
        """Initialize a new Git repository at the given path.

        Parameters
        ----------
        branch : str | None, optional
            An optional initial branch name to use for the repository.  If None (the
            default), then the Git installation's default branch will be used (e.g.
            "master" or "main").
        bare : bool, optional
            Whether to create a bare repository (default is True).  If false, then a
            standard repository with a working tree will be created instead.

        Raises
        ------
        CommandError
            If the git command fails.
        """
        self.git_dir.mkdir(parents=True, exist_ok=True)
        cmd = ["git", "init", "--quiet"]
        if branch is not None:
            cmd.extend(["--initial-branch", branch])
        if bare:
            cmd.append("--bare")
        cmd.append(str(self.git_dir))
        await run(cmd)

    async def run(
        self,
        argv: list[str],
        *,
        check: bool = True,
        capture_output: bool | None = False,
        input: str | None = None,
        timeout: float | None = None,
        attempts: int = 1,
        delay: float = 0.1,
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
    ) -> CompletedProcess:
        """Run a git command as an asynchronous subprocess wrapper.

        Parameters
        ----------
        argv : list[str]
            The command and its arguments to run, excluding the initial "git".
        check : bool, optional
            Whether to raise a `CommandError` if the command fails (default is True).
            If false, then any errors will be ignored.
        capture_output : bool | None, optional
            If true, then all output will be redirected to the returned
            `CompletedProcess` or `CommandError`, and excluded from the inherited
            stdout/stderr streams.  If false (the default), then the opposite is the
            case, and the returned `CompletedProcess` or `CommandError` will not
            include any captured output.  If None, then output will be "tee'd" to both
            the console and the returned objects simultaneously.  Note that teeing
            output in this way may break TTY behavior for some commands, and is not
            recommended for interactive use.
        input : str | None, optional
            Input to send to the command's stdin (default is None).
        timeout : float | None, optional
            An optional timeout in seconds to wait for the command to complete before
            raising a `TimeoutExpired` exception.  Default is None, which means to wait
            indefinitely.  If zero or negative, a `TimeoutExpired` exception will be
            raised immediately.  Note that this does not reset between `attempts`, so
            the total time spent on retries counts against the timeout.
        attempts : int, optional
            The total number of times to attempt the command.  Defaults to 1, which
            means no retries.  If greater than 1, then any command that exits with a
            nonzero exit code will be re-run after a short delay, up to the specified
            number of times in total.
        delay : float, optional
            The delay in seconds to wait between retries when `attempts` is greater
            than 1.  Default is 0.1 seconds.  Must be non-negative.
        cwd : Path | None, optional
            An optional working directory to run the command in.  If None (the default),
            then the current working directory will be used.
        env : Mapping[str, str] | None, optional
            An optional environment dictionary to use for the command.  If None (the
            default), then the current process's environment will be used.

        Returns
        -------
        CompletedProcess
            The completed process result.

        Raises
        ------
        CommandError
            If the command fails and `check` is True.
        TimeoutExpired
            If the command does not complete within the specified timeout.
        OSError
            If we failed to open the subprocess or its output streams.
        """
        return await run(
            ["git", "--git-dir", str(self.git_dir), *argv],
            check=check,
            capture_output=capture_output,
            input=input,
            timeout=timeout,
            attempts=attempts,
            delay=delay,
            cwd=cwd,
            env=env,
        )

    async def git_path(self, path: str, *, cwd: Path | None = None) -> Path:
        """Resolve a git-path using `git rev-parse --git-path`.

        Parameters
        ----------
        path : str
            The git-path expression to resolve (e.g. `hooks/pre-commit`).
        cwd : Path | None, optional
            Optional working directory for relative path resolution semantics.

        Returns
        -------
        Path
            The resolved absolute filesystem path.

        Raises
        ------
        ValueError
            If git returned an empty path.
        CommandError
            If the git command fails.
        """
        result = await self.run(
            ["rev-parse", "--path-format=absolute", "--git-path", path],
            capture_output=True,
            cwd=cwd,
        )
        text = result.stdout.strip()
        if not text:
            raise ValueError(f"empty --git-path output for {path!r}")
        resolved = Path(text).expanduser()
        if not resolved.is_absolute():
            base = cwd if cwd is not None else self.root
            resolved = (base / resolved).resolve()
        else:
            resolved = resolved.resolve()
        return resolved

    def _parse_bool(self, stdout: str) -> bool:
        value = stdout.strip().lower()
        if value == "true":
            return True
        if value == "false":
            return False
        raise ValueError(f"invalid git boolean output: {stdout!r}")

    @staticmethod
    async def supports_relative_paths() -> bool:
        """
        Returns
        -------
        bool
            True if both `git worktree add` and `git worktree move` support
            `--relative-paths` according to their help output, false otherwise.
        """
        add_help = await run(
            ["git", "worktree", "add", "-h"],
            check=False,
            capture_output=True,
        )
        add_text = f"{add_help.stdout}\n{add_help.stderr}".lower()
        if add_help.returncode != 0 or "--relative-paths" not in add_text:
            return False
        move_help = await run(
            ["git", "worktree", "move", "-h"],
            check=False,
            capture_output=True,
        )
        move_text = f"{move_help.stdout}\n{move_help.stderr}".lower()
        return move_help.returncode == 0 and "--relative-paths" in move_text

    @staticmethod
    async def default_branch() -> str:
        """
        Returns
        -------
        str
            The default branch name configured for this git installation.

        Raises
        ------
        CommandError
            If git commands fail while probing default branch behavior.
        ValueError
            If the default branch could not be determined from git output.
        """
        branch = await run(["git", "var", "GIT_DEFAULT_BRANCH"], capture_output=True)
        result = branch.stdout.strip()
        if not result:
            raise ValueError("default Git branch name could not be determined")
        return result

    async def head_branch(self) -> str | None:
        """
        Returns
        -------
        str | None
            The short branch name of the current HEAD, or None if HEAD is detached.

        Raises
        ------
        CommandError
            If the git command fails with an error.
        ValueError
            If we failed to parse the output or got an empty branch name.
        """
        # attached HEAD: try to read symbolic ref directly
        result = await self.run(
            ["symbolic-ref", "--quiet", "--short", "HEAD"],
            check=False,
            capture_output=True,
        )
        if result.returncode == 0:
            text = result.stdout.strip()
            if not text:
                raise ValueError("empty symbolic-ref output for HEAD")
            return text
        if result.returncode != 1:
            raise CommandError(result.returncode, result.args, result.stdout, result.stderr)

        # detached HEAD: let caller decide what to do
        return None

    async def is_bare(self) -> bool:
        """
        Returns
        -------
        bool
            True if this repository is a bare repository, false otherwise.

        Raises
        ------
        CommandError
            If the git command fails.
        ValueError
            If we failed to parse the output.
        """
        result = await self.run(
            ["rev-parse", "--is-bare-repository"],
            capture_output=True,
        )
        value = result.stdout.strip().lower()
        if value == "true":
            return True
        if value == "false":
            return False
        raise ValueError(f"invalid --is-bare-repository output: {result.stdout!r}")

    async def branches(self) -> frozenset[str]:
        """
        Returns
        -------
        frozenset[str]
            A set of all (short) branch names in the repository.  Note that this only
            includes branches under `refs/heads/`, and not other refs like tags or
            remotes.

        Raises
        ------
        CommandError
            If the git command fails.
        """
        result = await self.run(
            ["for-each-ref", "--format=%(refname:short)", "refs/heads"],
            capture_output=True,
        )
        out = {line.strip() for line in result.stdout.splitlines()}
        out.discard("")  # remove empty lines if any
        return frozenset(out)

    async def worktrees(self) -> tuple[GitRepository.Worktree, ...]:
        """List all local worktrees for the given Git directory.

        Returns
        -------
        tuple[GitRepository.Worktree, ...]
            A tuple of worktree entries.  Includes both attached (with branch) and
            detached (without branch) worktrees, which may be filtered by the caller as
            needed.
        """
        out: list[GitRepository.Worktree] = []
        path: Path | None = None
        branch: str | None = None
        result = await self.run(
            ["worktree", "list", "--porcelain"],
            capture_output=True,
        )
        for raw in result.stdout.splitlines():
            line = raw.strip()
            if not line:
                if path is not None:
                    out.append(self.Worktree(path=path, branch=branch))
                path = None
                branch = None
                continue
            if line.startswith("worktree "):
                path = Path(line[len("worktree "):]).expanduser().resolve()
                continue
            if line.startswith(f"branch {GIT_REF_HEADS_PREFIX}"):
                branch = line[len("branch ") + len(GIT_REF_HEADS_PREFIX):]
        if path is not None:
            out.append(self.Worktree(path=path, branch=branch))
        return tuple(out)

    async def _current_worktree_state(self) -> dict[str, Path]:
        current: dict[str, Path] = {}
        for wt in await self.worktrees():
            if wt.branch is None:
                continue
            existing = current.setdefault(wt.branch, wt.path)
            if existing != wt.path:
                raise FileExistsError(
                    f"multiple worktrees mapped to branch '{wt.branch}': "
                    f"{existing} and {wt.path}"
                )
        return current

    def _intended_worktree_changes(
        self,
        updates: Sequence[GitRefUpdate]
    ) -> tuple[list[str], list[str], list[tuple[str, str]]]:
        # get creation/destruction intent from transaction updates
        _created: dict[str, list[str]] = {}
        _destroyed: dict[str, list[str]] = {}
        created: list[str] = []
        destroyed: list[str] = []
        for update in updates:
            if update.created:
                created.append(update.branch)
                _created.setdefault(update.new, []).append(update.branch)
            elif update.destroyed:
                destroyed.append(update.branch)
                _destroyed.setdefault(update.old, []).append(update.branch)

        # infer rename hints from unambiguous create + destroy pairs on the same object
        renamed: list[tuple[str, str]] = []
        for oid in sorted(set(_created) & set(_destroyed)):
            c = _created[oid]
            d = _destroyed[oid]
            if len(c) == 1 and len(d) == 1:
                old_branch = d[0]
                new_branch = c[0]
                renamed.append((old_branch, new_branch))
                destroyed.remove(old_branch)
                created.remove(new_branch)

        return created, destroyed, renamed

    def _filter_worktree_conflicts(
        self,
        desired: dict[str, Path],
        current: dict[str, Path],
        created: list[str],
    ) -> dict[str, Path]:
        # sort branches by conflict priority, then filter out any whose slash-separated
        # paths would create a nested worktree conflicts
        winners: list[str] = []
        for branch in sorted(desired, key=lambda b: (
            0 if b in current else 1,  # prioritize existing
            0 if b not in created else 1,  # ... then prioritize non-created branches
            b,  # ... then break ties lexically
        )):
            conflict: str | None = None
            for winner in winners:
                if branch == winner:
                    continue
                left_parts = branch.split("/")
                right_parts = winner.split("/")
                min_len = min(len(left_parts), len(right_parts))
                if left_parts[:min_len] == right_parts[:min_len]:
                    conflict = winner
                    break
            if conflict is None:
                winners.append(branch)
                continue
            print(
                f"bertrand: skipping branch '{branch}' due nested path conflict with "
                f"'{conflict}'",
                file=sys.stderr
            )

        return {branch: desired[branch] for branch in winners}

    def _clean_worktree_parents(self, path: Path) -> None:
        # clean up now-empty parent directories up to project root to account for
        # branch names that contain path separators
        cursor = path.parent
        while cursor != self.root:
            try:
                if any(cursor.iterdir()):
                    break
                cursor.rmdir()
            except OSError:
                break
            cursor = cursor.parent

    async def _worktree_belongs_to_repo(self, path: Path, env: dict[str, str]) -> bool:
        result = await run(
            ["git", "-C", str(path), "rev-parse", "--git-common-dir"],
            check=False,
            capture_output=True,
            env=env,
        )
        if result.returncode != 0:
            return False
        owner = Path(result.stdout.strip()).expanduser()
        if not owner.is_absolute():
            owner = path / owner
        return self.git_dir == owner.expanduser().resolve()

    async def _strip_env(self, env: dict[str, str] | None = None) -> dict[str, str]:
        """Remove repo-local git environment variables from the given environment mapping.

        Parameters
        ----------
        env : dict[str, str] | None, optional
            The environment mapping to strip git variables from.  If None, the current
            process environment will be used.  Defaults to None.

        Returns
        -------
        dict[str, str]
            The filtered environment variables with repo-local keys removed.
        """
        env = dict(os.environ if env is None else env)
        local = await self.run(
            ["rev-parse", "--local-env-vars"],
            check=False,
            capture_output=True,
            env=env
        )
        if local.returncode == 0:
            keys = [key.strip() for key in local.stdout.splitlines() if key.strip()]
        else:
            keys = ["GIT_DIR", "GIT_WORK_TREE", "GIT_COMMON_DIR"]  # best-effort fallback
        for key in keys:
            env.pop(key, None)
        return env

    async def create_worktree(
        self,
        branch: str,
        *,
        target: Path | None = None,
        create_branch: bool = True,
        quiet: bool = False,
    ) -> None:
        """Create a new worktree for the given branch at the specified target path.

        Parameters
        ----------
        branch : str
            The short branch name to create a worktree for.
        target : Path | None, optional
            The target path to create the worktree at.  Must not already exist.
        create_branch : bool, optional
            If True (the default), then the branch will be created if it does not
            already exist.  If False, then the branch must already exist in the
            repository.
        quiet : bool, optional
            If True, then suppress any non-error output from the git command.  Default
            is False.

        Raises
        ------
        FileExistsError
            If the target path already exists.
        CommandError
            If the git command fails.
        """
        if target is None:
            target = self.root / branch
        if target.exists():
            raise FileExistsError("path already exists")
        target.parent.mkdir(parents=True, exist_ok=True)
        cmd = ["worktree", "add", "--relative-paths"]
        if create_branch:
            if branch not in await self.branches():
                cmd.extend(["-b", branch, str(target)])
            else:
                cmd.extend([str(target), branch])
        else:
            cmd.extend([str(target), branch])
        await self.run(cmd, capture_output=quiet)

    async def move_worktree(
        self,
        branch: str,
        *,
        source: Path | None = None,
        target: Path | None = None,
    ) -> None:
        """Move the worktree for the given branch from the source path to the target
        path.

        Parameters
        ----------
        branch : str
            The short branch name to move the worktree for.
        source : Path | None, optional
            The current path of the worktree to move.  If None, the path will be derived
            from the current worktree state for the given branch.  Defaults to None.
        target : Path | None, optional
            The destination path for the worktree.  If None, the worktree will be moved
            to its default location based on the branch name, if it is not already
            there.  Defaults to None.

        Raises
        ------
        FileNotFoundError
            If the source path does not exist or could not be derived from the current
            worktree state.
        NotADirectoryError
            If the source path or target path exists but is not a directory.
        FileExistsError
            If the target path already exists, and is not the same as the source path.
        """
        if source is None:
            for wt in await self.worktrees():
                if wt.branch == branch:
                    source = wt.path
                    break
            if source is None:
                raise FileNotFoundError(f"no worktree found for branch '{branch}'")
        if not source.exists():
            raise FileNotFoundError(f"worktree path does not exist: {source}")
        if not source.is_dir():
            raise NotADirectoryError(f"worktree is not a directory: {source}")

        if target is None:
            target = self.root / branch
        if target == source:
            return
        if target.exists():
            raise FileExistsError(f"target path already exists: {target}")

        target.parent.mkdir(parents=True, exist_ok=True)
        await self.run(
            ["worktree", "move", "--relative-paths", str(source), str(target)],
            capture_output=True
        )
        self._clean_worktree_parents(source)

    async def destroy_worktree(
        self,
        branch: str,
        *,
        target: Path | None = None,
    ) -> bool:
        """Destroy the worktree for the given branch, if it exists and is clean.

        Parameters
        ----------
        branch : str
            The short branch name to destroy the worktree for.
        target : Path | None, optional
            An optional path to the worktree to destroy.  If None (the default), then
            the path will be derived from the current worktree state for the given
            branch.

        Returns
        -------
        bool
            True if the worktree was successfully destroyed or did not exist, false if
            the worktree exists but could not be destroyed due to dirty state.

        Raises
        ------
        FileNotFoundError
            If the target path does not exist or could not be derived from the current
            worktree state.
        NotADirectoryError
            If the target path exists but is not a directory.
        RuntimeError
            If the target path does not belong to this repository.
        """
        if target is None:
            for wt in await self.worktrees():
                if wt.branch == branch:
                    target = wt.path
                    break
            if target is None:
                raise FileNotFoundError(f"no worktree found for branch '{branch}'")
        if not target.exists():
            raise FileNotFoundError(f"worktree path does not exist: {target}")
        if not target.is_dir():
            raise NotADirectoryError(f"worktree is not a directory: {target}")

        # verify that the worktree is clean and objectively belongs to this repository
        # before attempting deletion
        env = await self._strip_env()
        if not await self._worktree_belongs_to_repo(target, env):
            raise RuntimeError(
                f"worktree path does not belong to this repository: {target}"
            )
        clean = await run(
            ["git", "-C", str(target), "status", "--porcelain"],
            capture_output=True,
            env=env,
        )
        if clean.stdout.strip():
            return False

        # remove the worktree using git, which will also properly clean up the
        # associated gitdir and any linked metadata
        await self.run(["worktree", "remove", str(target)], capture_output=True)
        self._clean_worktree_parents(target)
        return True

    async def sync_worktrees(self, updates: Sequence[GitRefUpdate] = ()) -> None:
        """Converge worktrees to the authoritative branch set using a hybrid
        intent-first delta pass.

        Parameters
        ----------
        updates : Sequence[GitRefUpdate], optional
            The parsed reference updates received from git on stdin, which will be used
            to derive explicit intent for branch creations and destructions, as well as
            implicit hints for branch renames where creation and destruction are paired
            on the same object.  If omitted, then convergence will transform directly
            from the current state to the desired state without any intent-based
            guidance.
        """
        # non-bare repositories are treated as single-worktree mode
        if not await self.is_bare():
            return

        # derive current and desired branch-to-path mappings
        current = await self._current_worktree_state()
        desired = {branch: (self.root / branch) for branch in await self.branches()}

        # derive explicit intent from transaction updates, preserving order
        created, destroyed, renamed = self._intended_worktree_changes(updates)
        desired = self._filter_worktree_conflicts(desired, current, created)

        # apply rename hints first (when they map cleanly to current state)
        for old_branch, new_branch in renamed:
            source = current.get(old_branch)
            if source is None:
                continue
            target = desired.get(new_branch)
            if target is None or new_branch in current:
                continue
            try:
                await self.move_worktree(new_branch, source=source, target=target)
                current.pop(old_branch, None)
                current[new_branch] = target
            except Exception as err:
                print(
                    f"bertrand: failed to move worktree for branch '{new_branch}' from "
                    f"{source} to {target}:\n{err}"
                )

        # apply explicit destroys for branches still present in current state
        for branch in destroyed:
            path = current.get(branch)
            if path is None or branch in desired:
                continue
            try:
                if await self.destroy_worktree(branch, target=path):
                    current.pop(branch, None)
            except Exception as err:
                print(
                    f"bertrand: failed to destroy worktree for branch '{branch}' at "
                    f"{path}:\n{err}"
                )

        # apply explicit creates for branches that are still missing
        for branch in created:
            if branch in current or branch not in desired:
                continue
            target = desired[branch]
            try:
                await self.create_worktree(branch, target=target, create_branch=True)
                current[branch] = target
            except Exception as err:
                print(
                    f"bertrand: failed to create worktree for branch '{branch}' at "
                    f"{target}:\n{err}"
                )

        # remove branches no longer present in the repository
        stale = set(current) - set(desired)
        for branch in sorted(stale):
            path = current[branch]
            try:
                if await self.destroy_worktree(branch, target=path):
                    current.pop(branch, None)
            except Exception as err:
                print(
                    f"bertrand: failed to destroy worktree for branch '{branch}' at "
                    f"{path}:\n{err}"
                )

        # move branches that are present but located at non-canonical paths
        shared = set(current) & set(desired)
        for branch in sorted(shared):
            source = current[branch]
            target = desired[branch]
            if source == target:
                continue
            try:
                await self.move_worktree(branch, source=source, target=target)
                current[branch] = target
            except Exception as err:
                print(
                    f"bertrand: failed to move worktree for branch '{branch}' from "
                    f"{source} to {target}:\n{err}"
                )

        # create worktrees for branches that don't yet have one
        missing = set(desired) - set(current)
        for branch in sorted(missing):
            target = desired[branch]
            try:
                await self.create_worktree(branch, target=target, create_branch=False)
                current[branch] = target
            except Exception as err:
                print(
                    f"bertrand: failed to create worktree for branch '{branch}' at "
                    f"{target}:\n{err}"
                )
