# bertrand-managed: bertrand_git.py
# NOTE: the above marker is used to allow Bertrand to automatically rewrite this file
# in-place when the packaged version is updated, rather than warning in the event of a
# mismatch.  All hooks must have a similar marker.
"""A selection of Git-related utilities for use in the Bertrand CLI and custom Git
hooks.

This file will be automatically copied from the `bertrand` package metadata into the
`.git/hooks/` directory for any repository generated by `bertrand init`, etc.  It is
intended to be imported by custom Git hooks, so that they don't need to re-implement
common Git-related functionality themselves, and can remain standalone from the rest of
the `bertrand` codebase.  This is critical, because importing code from `bertrand`
within a git hook could cause ordinary git operations to fail if `bertrand` is not
installed in the current environment.
"""
from __future__ import annotations

import asyncio
import os
import pwd
import re
import shlex
import shutil
import subprocess
import sys
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Mapping, TextIO

# pylint: disable=redefined-builtin


#######################
####    GENERAL    ####
#######################


# NOTE: These utilities don't specifically have to do with Git, but are included here
# because they don't have any dependencies, and can be reused by Git hooks to improve
# functionality without breaking isolation.  The same utilities are exported to the
# main CLI, so there's no risk of duplication.


class CompletedProcess(subprocess.CompletedProcess[str]):
    """A subclass of `subprocess.CompletedProcess` that prints the command and its
    output when converted to a string.
    """
    def __str__(self) -> str:
        out = [
            f"Exit code {self.returncode} from command:\n\n"
            f"    {' '.join(shlex.quote(a) for a in self.args)}"
        ]
        if self.stderr:
            out.append(self.stderr.strip())
        return "\n\n".join(out)


class CommandError(subprocess.CalledProcessError):
    """A subclass of `subprocess.CalledProcessError` that prints the command and its
    output when converted to a string.
    """
    def __str__(self) -> str:
        out = [
            f"Exit code {self.returncode} from command:\n\n"
            f"    {' '.join(shlex.quote(a) for a in self.cmd)}"
        ]
        if self.stderr:
            out.append(self.stderr.strip())
        return "\n\n".join(out)


class TimeoutExpired(subprocess.TimeoutExpired):
    """A subclass of `subprocess.TimeoutExpired` that prints the command and any captured
    output when converted to a string.
    """
    def __str__(self) -> str:
        out = [
            f"Command timed out after {self.timeout} seconds:\n\n"
            f"    {' '.join(shlex.quote(a) for a in self.cmd)}"
        ]
        if self.output:
            out.append(self.output.strip())
        if self.stderr:
            out.append(str(self.stderr.strip()))
        return "\n\n".join(out)


@dataclass(frozen=True)
class User:
    """A simple structure representing a user identity by user ID and group ID.

    Attributes
    ----------
    uid : int
        The numeric user ID.
    gid : int
        The numeric group ID.
    name : str
        The username.
    home : Path
        The path to the user's home directory.
    """
    uid: int = field(init=False)
    gid: int = field(init=False)
    name: str = field(init=False)
    home: Path = field(init=False)

    def __post_init__(self) -> None:
        euid = os.geteuid()
        sudo_uid = os.environ.get("SUDO_UID")
        sudo_user = os.environ.get("SUDO_USER")
        if euid == 0 and sudo_uid:
            object.__setattr__(self, 'uid', int(sudo_uid))
            pw = pwd.getpwuid(self.uid)
            object.__setattr__(self, 'gid', pw.pw_gid)
            object.__setattr__(self, 'name', sudo_user or pw.pw_name)
            object.__setattr__(self, 'home', Path(pw.pw_dir))
        else:
            object.__setattr__(self, 'uid', os.getuid())
            pw = pwd.getpwuid(self.uid)
            object.__setattr__(self, 'gid', pw.pw_gid)
            object.__setattr__(self, 'name', pw.pw_name)
            object.__setattr__(self, 'home', Path(pw.pw_dir))


def atomic_write_text(
    path: Path,
    text: str,
    encoding: str | None = None,
    private: bool = False,
) -> None:
    """Atomically write text to a file, avoiding race conditions and partial writes.

    Parameters
    ----------
    path : Path
        The path to write to.
    text : str
        The text to write.
    encoding : str | None, optional
        The text encoding to use (default is None, which uses the system default).
    private : bool, optional
        Whether to set private permissions (0600) on the written file, by default False.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.tmp.{uuid.uuid4().hex}")
    tmp.write_text(text, encoding=encoding)
    try:
        with tmp.open("r+", encoding=encoding) as f:
            f.flush()
            os.fsync(f.fileno())
    except OSError:
        pass
    if private:
        try:
            tmp.chmod(0o600)
        except OSError:
            pass
    tmp.replace(path)


def atomic_write_bytes(path: Path, data: bytes, private: bool = False) -> None:
    """Atomically write bytes to a file, avoiding race conditions and partial writes.

    Parameters
    ----------
    path : Path
        The path to write to.
    data : bytes
        The bytes to write.
    private : bool, optional
        Whether to set private permissions (0600) on the written file, by default False.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.tmp.{uuid.uuid4().hex}")
    tmp.write_bytes(data)
    try:
        with tmp.open("r+b") as f:
            f.flush()
            os.fsync(f.fileno())
    except OSError:
        pass
    if private:
        try:
            tmp.chmod(0o600)
        except OSError:
            pass
    tmp.replace(path)


def can_escalate() -> bool:
    """
    Returns
    -------
    bool
        True if privilege escalation is possible on the current system, false
        otherwise.
    """
    return os.name == "posix" and bool(shutil.which("sudo") or shutil.which("doas"))


def confirm(prompt: str, *, assume_yes: bool = False) -> bool:
    """Ask the user for a yes/no confirmation for a given prompt.

    Parameters
    ----------
    prompt : str
        The prompt to display to the user.
    assume_yes : bool, optional
        If True, automatically return True without prompting the user.  Default is
        False.

    Returns
    -------
    bool
        True if the user confirmed yes, false otherwise.
    """
    if assume_yes:
        return True
    try:
        response = input(prompt).strip().lower()
    except EOFError:
        return False
    return response in {"y", "yes"}


def mkdir_private(path: Path) -> None:
    """Create a directory with private permissions (0700) if it does not already exist.

    Parameters
    ----------
    path : Path
        The path to create.
    """
    path.mkdir(parents=True, exist_ok=True)
    try:
        path.chmod(0o700)
    except OSError:
        pass


async def _tee(src: asyncio.StreamReader | None, sink: TextIO, buf_list: list[str]) -> None:
    if src is None:
        return
    while True:
        chunk = await src.readline()
        if not chunk:
            break
        text = chunk.decode("utf-8", errors="replace")
        buf_list.append(text)
        try:
            sink.write(text)
            sink.flush()
        except OSError:
            pass


async def _write_stdin(dst: asyncio.StreamWriter | None, data: str) -> None:
    if dst is None:
        return
    try:
        dst.write(data.encode("utf-8", errors="replace"))
        await dst.drain()
    except (BrokenPipeError, ConnectionResetError, OSError):
        pass
    finally:
        try:
            dst.close()
            await dst.wait_closed()
        except (AttributeError, RuntimeError, OSError):
            pass


async def run(
    argv: list[str],
    *,
    check: bool = True,
    capture_output: bool | None = False,
    input: str | None = None,
    timeout: float | None = None,
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> CompletedProcess:
    """An asynchronous subprocess wrapper that defaults to text mode and properly
    formats errors.

    Parameters
    ----------
    argv : list[str]
        The command and its arguments to run.
    check : bool, optional
        Whether to raise a `CommandError` if the command fails (default is True).  If
        false, then any errors will be ignored.
    capture_output : bool | None, optional
        If true, then all output will be redirected to the returned `CompletedProcess`
        or `CommandError`, and excluded from the inherited stdout/stderr streams.  If
        false (the default), then the opposite is the case, and the returned
        `CompletedProcess` or `CommandError` will not include any captured output.  If
        None, then output will be "tee'd" to both the console and the returned objects
        simultaneously.  Note that teeing output in this way may break TTY behavior for
        some commands, and is not recommended for interactive use.
    input : str | None, optional
        Input to send to the command's stdin (default is None).
    timeout : float | None, optional
        An optional timeout in seconds to wait for the command to complete before
        raising a `TimeoutExpired` exception.  Default is None, which means to wait
        indefinitely.
    cwd : Path | None, optional
        An optional working directory to run the command in.  If None (the default),
        then the current working directory will be used.
    env : Mapping[str, str] | None, optional
        An optional environment dictionary to use for the command.  If None (the
        default), then the current process's environment will be used.

    Returns
    -------
    CompletedProcess
        The completed process result.

    Raises
    ------
    CommandError
        If the command fails and `check` is True.
    TimeoutExpired
        If the command does not complete within the specified timeout.
    OSError
        If we failed to open the subprocess or its output streams.
    """
    if timeout is not None and timeout < 0:
        raise TimeoutExpired(cmd=argv, timeout=timeout, output=None, stderr=None)

    # capture_output=False -> inherit terminal streams and do not capture output
    if capture_output is False:
        proc = await asyncio.create_subprocess_exec(
            *argv,
            stdin=asyncio.subprocess.PIPE if input is not None else None,
            stdout=None,
            stderr=None,
            cwd=cwd,
            env=env,
        )
        try:
            input_bytes = None if input is None else input.encode("utf-8", errors="replace")
            try:
                await asyncio.wait_for(proc.communicate(input_bytes), timeout=timeout)
            except asyncio.TimeoutError as err:
                proc.kill()
                await proc.communicate()
                raise TimeoutExpired(
                    cmd=argv,
                    timeout=timeout or 0.0,
                    output=None,
                    stderr=None
                ) from err
        finally:
            if proc.returncode is None:
                proc.kill()
                await proc.wait()

        assert proc.returncode is not None
        result = CompletedProcess(argv, proc.returncode, "", "")
        if check and result.returncode != 0:
            raise CommandError(result.returncode, argv, "", "")
        return result

    # capture_output=True -> full capture with no tee
    if capture_output is True:
        proc = await asyncio.create_subprocess_exec(
            *argv,
            stdin=asyncio.subprocess.PIPE if input is not None else None,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=cwd,
            env=env,
        )
        try:
            input_bytes = None if input is None else input.encode("utf-8", errors="replace")
            try:
                stdout_raw, stderr_raw = await asyncio.wait_for(
                    proc.communicate(input_bytes),
                    timeout=timeout,
                )
            except asyncio.TimeoutError as err:
                proc.kill()
                stdout_raw, stderr_raw = await proc.communicate()
                raise TimeoutExpired(
                    cmd=argv,
                    timeout=timeout or 0.0,
                    output=stdout_raw.decode("utf-8", errors="replace") or None,
                    stderr=stderr_raw.decode("utf-8", errors="replace") or None,
                ) from err
        finally:
            if proc.returncode is None:
                proc.kill()
                await proc.wait()

        assert proc.returncode is not None
        stdout_text = stdout_raw.decode("utf-8", errors="replace")
        stderr_text = stderr_raw.decode("utf-8", errors="replace")
        result = CompletedProcess(argv, proc.returncode, stdout_text, stderr_text)
        if check and result.returncode != 0:
            raise CommandError(result.returncode, argv, stdout_text, stderr_text)
        return result

    # capture_output=None -> tee streams while capturing for return/errors
    proc = await asyncio.create_subprocess_exec(
        *argv,
        stdin=asyncio.subprocess.PIPE if input is not None else None,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=cwd,
        env=env,
    )
    stdout_lines: list[str] = []
    stderr_lines: list[str] = []
    tasks: list[asyncio.Task[None]] = [
        asyncio.create_task(_tee(proc.stdout, sys.stdout, stdout_lines)),
        asyncio.create_task(_tee(proc.stderr, sys.stderr, stderr_lines)),
    ]
    if input is not None:
        tasks.append(asyncio.create_task(_write_stdin(proc.stdin, input)))

    try:
        try:
            await asyncio.wait_for(proc.wait(), timeout=timeout)
        except asyncio.TimeoutError as err:
            proc.kill()
            await proc.wait()
            for task in tasks:
                await task
            stdout_text = "".join(stdout_lines)
            stderr_text = "".join(stderr_lines)
            raise TimeoutExpired(
                cmd=argv,
                timeout=timeout or 0.0,
                output=stdout_text or None,
                stderr=stderr_text or None,
            ) from err
    finally:
        if proc.returncode is None:
            proc.kill()
            await proc.wait()
        for task in tasks:
            await task

    stdout_text = "".join(stdout_lines)
    stderr_text = "".join(stderr_lines)
    assert proc.returncode is not None
    result = CompletedProcess(argv, proc.returncode, stdout_text, stderr_text)
    if check and result.returncode != 0:
        raise CommandError(result.returncode, argv, stdout_text, stderr_text)
    return result


SANITIZE = re.compile(r"[^a-zA-Z0-9._]+")


def sanitize_name(name: str, *, replace: str = "_") -> str:
    """Replace any characters in the given name that are not alphanumeric, '.', or '_'
    with the specified replacement character, and then strip leading and trailing
    replacement characters from the result.

    Parameters
    ----------
    name : str
        The name to sanitize.
    replace : str, optional
        The character to use as a replacement for invalid characters.  Default is '_'.

    Returns
    -------
    str
        The sanitized name.
    """
    return SANITIZE.sub(replace, name).strip(replace)


def sudo(argv: list[str], *, non_interactive: bool = False) -> list[str]:
    """Return a command with privilege escalation prepended when needed.

    Parameters
    ----------
    argv : list[str]
        The command and its arguments.
    non_interactive : bool, optional
        If True, add non-interactive flags for the selected escalator so it fails
        immediately instead of prompting for a password.

    Returns
    -------
    list[str]
        A new list containing either the original command (when no escalation is
        needed/available) or the escalated command.

    Notes
    -----
    Escalation is only attempted on POSIX systems for non-root users.  The selection
    order is `sudo`, then `doas`.
    """
    # no-op outside POSIX, when already root, or when no supported escalator is found
    if os.name != "posix" or os.geteuid() == 0:
        return argv.copy()
    escalator = None
    if shutil.which("sudo"):
        escalator = "sudo"
    elif shutil.which("doas"):
        escalator = "doas"
    if escalator is None:
        return argv.copy()

    out = [escalator]
    if non_interactive:
        out.append("-n")
    out.extend(argv)
    return out


###################
####    GIT    ####
###################


# NOTE: These utilities are intended to be imported by Git hooks via
# `from bertrand_git import ...` (notice no relative paths/leading dot).  The
# `bertrand init` command ensures that this file is copied into the `.git/hooks/`
# directory alongside the hooks themselves, so that the import will always resolve
# properly.  Note that it IS NOT SAFE to import code from third-party libraries or
# across hooks, since the hook names may be rewritten in order to conform to Git's
# expectations.  This is the ONLY file that Bertrand guarantees to be importable from
# downstream hooks.


HEADS_PREFIX = "refs/heads/"
STATES = {"prepared", "committed", "aborted"}


@dataclass(frozen=True)
class RefUpdate:
    """A single reference update received from git on stdin."""
    old: str
    new: str
    ref: str

    @property
    def is_head(self) -> bool:
        """
        Returns
        -------
        bool
            True if this update targets `refs/heads/*`.
        """
        return self.ref.startswith(HEADS_PREFIX)

    @property
    def branch(self) -> str:
        """
        Returns
        -------
        str
            The short branch name for `refs/heads/*` updates.
        """
        return self.ref[len(HEADS_PREFIX):]

    @property
    def created(self) -> bool:
        """
        Returns
        -------
        bool
            True if this update created a new ref.
        """
        return all((c == "0" for c in self.old)) and any((c != "0" for c in self.new))

    @property
    def destroyed(self) -> bool:
        """
        Returns
        -------
        bool
            True if this update deleted an existing ref.
        """
        return any((c != "0" for c in self.old)) and all((c == "0" for c in self.new))

    @classmethod
    def parse(cls, stdin: str) -> list[RefUpdate]:
        """Parse and validate transaction update lines from stdin.

        Parameters
        ----------
        stdin : str
            The raw stdin input containing reference update lines, typically read from
            the `reference-transaction` hook's standard input stream.

        Returns
        -------
        list[RefUpdate]
            A list of parsed reference updates.

        Raises
        ------
        ValueError
            If any line is malformed.
        """
        updates: list[RefUpdate] = []
        for index, raw in enumerate(stdin.splitlines(), start=1):
            line = raw.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) != 3:
                raise ValueError(
                    f"malformed git transaction line {index}: expected "
                    f"'<old> <new> <ref>', got: {raw!r}"
                )
            old, new, ref = (part.strip() for part in parts)
            if not ref:
                raise ValueError(
                    f"malformed git transaction line {index}: ref must not be empty"
                )
            updates.append(cls(old=old, new=new, ref=ref))
        return updates


@dataclass(frozen=True)
class Worktree:
    """A parsed entry from `git worktree list --porcelain`.

    Attributes
    ----------
    path : Path
        The absolute path to the worktree checkout.
    branch : str | None
        The short branch name if this worktree is attached to `refs/heads/*`,
        otherwise None.
    """
    path: Path
    branch: str | None = None


async def git(
    argv: list[str],
    *,
    check: bool = True,
    capture_output: bool | None = False,
    input: str | None = None,
    timeout: float | None = None,
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> CompletedProcess:
    """Run a git command as an asynchronous subprocess wrapper.

    Parameters
    ----------
    argv : list[str]
        The command and its arguments to run, excluding the initial "git".
    check : bool, optional
        Whether to raise a `CommandError` if the command fails (default is True).  If
        false, then any errors will be ignored.
    capture_output : bool | None, optional
        If true, then all output will be redirected to the returned `CompletedProcess`
        or `CommandError`, and excluded from the inherited stdout/stderr streams.  If
        false (the default), then the opposite is the case, and the returned
        `CompletedProcess` or `CommandError` will not include any captured output.  If
        None, then output will be "tee'd" to both the console and the returned objects
        simultaneously.  Note that teeing output in this way may break TTY behavior for
        some commands, and is not recommended for interactive use.
    input : str | None, optional
        Input to send to the command's stdin (default is None).
    timeout : float | None, optional
        An optional timeout in seconds to wait for the command to complete before
        raising a `TimeoutExpired` exception.  Default is None, which means to wait
        indefinitely.
    cwd : Path | None, optional
        An optional working directory to run the command in.  If None (the default),
        then the current working directory will be used.
    env : Mapping[str, str] | None, optional
        An optional environment dictionary to use for the command.  If None (the
        default), then the current process's environment will be used.

    Returns
    -------
    CompletedProcess
        The completed process result.

    Raises
    ------
    CommandError
        If the command fails and `check` is True.
    TimeoutExpired
        If the command does not complete within the specified timeout.
    OSError
        If we failed to open the subprocess or its output streams.
    """
    return await run(
        ["git", *argv],
        check=check,
        capture_output=capture_output,
        input=input,
        timeout=timeout,
        cwd=cwd,
        env=env,
    )


async def git_strip_env(env: dict[str, str] | None = None) -> dict[str, str]:
    """Remove repo-local git environment variables from the given environment mapping.

    Parameters
    ----------
    env : dict[str, str] | None, optional
        The environment mapping to strip git variables from.  If None, the current
        process environment will be used.  Defaults to None.

    Returns
    -------
    dict[str, str]
        The filtered environment variables with repo-local keys removed.
    """
    env = dict(os.environ if env is None else env)
    local = await git(["rev-parse", "--local-env-vars"], check=False, capture_output=True, env=env)
    if local.returncode == 0:
        keys = [key.strip() for key in local.stdout.splitlines() if key.strip()]
    else:
        keys = ["GIT_DIR", "GIT_WORK_TREE", "GIT_COMMON_DIR"]  # best-effort fallback
    for key in keys:
        env.pop(key, None)
    return env


# TODO: the obvious surface area for this is a `Repository` class that takes the
# git-dir as an initializer, and exposes `branches()`, `worktrees()`, etc.


async def list_branches(git_dir: Path) -> list[str]:
    """List all branches in the given Git directory.

    Parameters
    ----------
    git_dir : Path
        The path to the Git directory.

    Returns
    -------
    list[str]
        A list of short branch names.  Note that this only includes branches under
        `refs/heads/`, and not other refs like tags or remotes.
    """
    result = await git(
        [
            "--git-dir", str(git_dir),
            "for-each-ref",
            "--format=%(refname:short)",
            "refs/heads",
        ],
        capture_output=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


async def list_worktrees(git_dir: Path) -> list[Worktree]:
    """List all local worktrees for the given Git directory, keyed by their attached
    branch name.

    Parameters
    ----------
    git_dir : Path
        The path to the Git directory.

    Returns
    -------
    list[Worktree]
        A list of worktree entries.  Only includes worktrees that are attached to
        `refs/heads/*` branches, and excludes any detached HEAD worktrees.
    """
    out: list[Worktree] = []
    path: Path | None = None
    branch: str | None = None
    result = await git(
        ["--git-dir", str(git_dir), "worktree", "list", "--porcelain"],
        capture_output=True,
    )
    for raw in result.stdout.splitlines():
        line = raw.strip()
        if not line:
            if path is not None:
                out.append(Worktree(path=path, branch=branch))
            path = None
            branch = None
            continue
        if line.startswith("worktree "):
            path = Path(line[len("worktree "):]).expanduser().resolve()
            continue
        if line.startswith(f"branch {HEADS_PREFIX}"):
            branch = line[len("branch ") + len(HEADS_PREFIX):]
    if path is not None:
        out.append(Worktree(path=path, branch=branch))
    return out


async def supports_relative_worktree_paths(*, cwd: Path | None = None) -> bool:
    """Probe `git worktree add/move` support for `--relative-paths`.

    Parameters
    ----------
    cwd : Path | None, optional
        Optional working directory for probe commands.

    Returns
    -------
    bool
        True if both `git worktree add` and `git worktree move` support
        `--relative-paths` according to their help output, false otherwise.
    """
    add_help = await git(
        ["worktree", "add", "-h"],
        check=False,
        capture_output=True,
        cwd=cwd,
    )
    if add_help.returncode != 0 or "--relative-paths" not in add_help.stdout.lower():
        return False
    move_help = await git(
        ["worktree", "move", "-h"],
        check=False,
        capture_output=True,
        cwd=cwd,
    )
    return move_help.returncode == 0 and "--relative-paths" in move_help.stdout.lower()




def parse_git_bool(stdout: str) -> bool:
    """Parse git boolean output (`true`/`false`) into a Python bool.

    Parameters
    ----------
    stdout : str
        Output text returned by git.

    Returns
    -------
    bool
        The parsed boolean value.

    Raises
    ------
    ValueError
        If the output is not one of `true` or `false`.
    """
    value = stdout.strip().lower()
    if value == "true":
        return True
    if value == "false":
        return False
    raise ValueError(f"invalid git boolean output: {stdout!r}")
