ARG BERTRAND={{ bertrand_major }}.{{ bertrand_minor }}.{{ bertrand_patch }}
ARG DEBUG=true
ARG DEV=true
ARG CPUS={{ cpus }}
FROM bertrand:${BERTRAND}.${DEBUG}.${DEV}.${CPUS}.{{ page_size_kib }}
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
WORKDIR {{ env_mount }}
COPY . {{ env_mount }}

{% for dep in dependency_copies %}
COPY --from={{ dep.image }} / {{ dep.target }}
{% endfor %}

{% if build_mounts %}
RUN {{ build_mounts | join(' \\\n    ') }} \
    bertrand build
{% else %}
RUN bertrand build
{% endif %}
