ARG BERTRAND={{ bertrand_major }}.{{ bertrand_minor }}.{{ bertrand_patch }}
ARG DEBUG=true
ARG DEV=true
ARG CPUS={{ cpus }}
FROM bertrand:${BERTRAND}.${DEBUG}.${DEV}.${CPUS}.{{ page_size_kib }}
{% for arg in build_args %}
ARG {{ arg.key }}
{% endfor %}
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \
    UV_CACHE_DIR={{ uv_cache }} \
    CONAN_HOME={{ conan_home }} \
    CCACHE_DIR={{ ccache_dir }}
WORKDIR {{ env_mount }}
COPY . {{ env_mount }}

{% for dep in dependency_copies %}
COPY --from={{ dep.image }} / {{ dep.target }}
{% endfor %}

RUN{% for mount in run_mounts %} --mount={{ mount }}{% endfor %} bertrand build{% for arg in build_args %} \
    --build-arg {{ arg.key }}="${{ "{" }}{{ arg.key }}{{ "}" }}"{% endfor %}
