# bertrand-managed: bertrand_git.py
# NOTE: the above marker is used to allow Bertrand to automatically rewrite this file
# in-place when the packaged version is updated, rather than warning in the event of a
# mismatch.  All hooks must have a similar marker.
"""A selection of core utilities for use in the Bertrand CLI and custom Git hooks.

This file will be automatically copied from the `bertrand` package distribution into
the `.git/hooks/` directory for any repository generated by `bertrand init`, etc.  It
is intended to be imported by custom Git hooks, so that they don't need to re-implement
common functionality themselves, and can stand alone with respect to the rest of the
`bertrand` codebase.  This is critical, because importing code from `bertrand` within
a git hook could cause ordinary git operations to fail if `bertrand` is not installed
in the current environment.
"""

from __future__ import annotations

import asyncio
import contextlib
import errno
import grp
import hashlib
import os
import pwd
import shlex
import shutil
import subprocess
import sys
import threading
import uuid
from collections.abc import Awaitable, Callable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path, PosixPath
from typing import TYPE_CHECKING, Any, Literal, Self, TextIO, cast

if TYPE_CHECKING:
    from types import TracebackType

if os.name == "nt":
    import msvcrt
else:
    import fcntl


# NOTE: The Git-related utilities are intended to be imported by Git hooks via
# `from bertrand_git import ...` (notice no relative paths/leading dot).  The
# `bertrand init` command ensures that this file is copied into the `.git/hooks/`
# directory alongside the hooks themselves, so that the import will always resolve
# properly.  Note that it IS NOT SAFE to import code from third-party libraries within
# hooks, or share code between them, since the hook names may be rewritten in order to
# conform to Git's expectations.  This is therefore the ONLY file that Bertrand
# guarantees to be importable from hooks, and it must not have any dependencies except
# the Python standard library.  Other utilities may be packaged within it in order to
# avoid duplication across hooks, but only if they conform to the same standards.
# Because this file has no dependencies, these utilities will also be exported to the
# main Bertrand CLI, so there's no further risk of duplication.


# generic utils
ROOT_DIR = Path(Path(sys.executable).anchor)
HOST_MOUNTS = ROOT_DIR / "proc" / "self" / "mountinfo"
INFINITY = float("inf")
NORMALIZE_ARCH = {
    "x86_64": "amd64",
    "amd64": "amd64",
    "aarch64": "arm64",
    "arm64": "arm64",
}
GIT_REF_HEADS_PREFIX = "refs/heads/"
GIT_REF_STATES: frozenset[GitRefState] = frozenset({"prepared", "committed", "aborted"})
GIT_REQUIRE_RELATIVE_PATHS = (
    "git worktree relative path support is required for bare repository mode, but "
    "this git version does not support '--relative-paths' for worktree creation and "
    "move operations.  Please upgrade git to a version that supports this feature "
    "(git 2.52+)."
)
LOCK_POLL_SECONDS = 0.1
LOCK_DEFAULT_PRIVILEGES = 0o600
LOCK_GUARD = threading.RLock()
HOST_LOCKS: dict[tuple[str, int], HostLock] = {}


# In-container path definitions for metadata and runtime control.
METADATA_DIR: PosixPath = PosixPath(".bertrand")
METADATA_FILE: PosixPath = METADATA_DIR / "env.json"
METADATA_LOCK: PosixPath = METADATA_DIR / ".lock"
METADATA_REPO_ID: PosixPath = METADATA_DIR / "repo_id"
METADATA_TMP: PosixPath = METADATA_DIR / "tmp"
WORKTREE_MOUNT: PosixPath = PosixPath("/bertrand")
PROJECT_MOUNT: PosixPath = PosixPath("/.bertrand")
CONTAINER_RUNTIME_MOUNT: PosixPath = PosixPath("/run/bertrand")
CONTAINER_TMP_MOUNT: PosixPath = PosixPath("/tmp/bertrand")
CONTAINER_ARTIFACT_MOUNT: PosixPath = CONTAINER_TMP_MOUNT / "artifacts"


# In-container environment variables for relevant configuration, which are set either
# at build time or upon starting the container context, and used to control the
# behavior of the bertrand CLI both inside and outside the container.
BERTRAND_ENV: str = "BERTRAND"  # "1" to mark as a Bertrand context
REPO_ID_ENV: str = "BERTRAND_REPO_ID"  # unique repository UUID
ENV_ID_ENV: str = "BERTRAND_ENV_ID"  # unique Bertrand environment UUID
IMAGE_ID_ENV: str = "BERTRAND_IMAGE_ID"  # unique OCI image ID
CONTAINER_ID_ENV: str = "BERTRAND_CONTAINER_ID"  # unique OCI container ID
PROJECT_ENV: str = "BERTRAND_PROJECT"  # host path to mounted project root
WORKTREE_ENV: str = "BERTRAND_WORKTREE"  # relative path to mounted worktree
# relative path to worktree's artifact directory
CONTAINER_RUNTIME_ENV: str = "BERTRAND_RUNTIME"


# Shared runtime identifiers and host paths.  These intentionally stay in this
# hook-safe module so installed Git hooks can use them without importing the rest of
# Bertrand.  Host-state convergence lives in `bertrand.env.host`.
BERTRAND_NAMESPACE = "bertrand"
BERTRAND_GROUP = "bertrand"
STATE_DIR = Path("/var/lib/bertrand")
HOST_ID_FILE = STATE_DIR / "host_id"
REPO_DIR = STATE_DIR / "repositories"
REPO_LOCK_EXT = Path("lock")
REPO_MOUNT_EXT = Path("mount")
BIN_DIR = STATE_DIR / "bin"
CACHE_DIR = STATE_DIR / "cache"
RUN_DIR = STATE_DIR / "run"
TOOLS_DIR = STATE_DIR / "tools"


# common type aliases for serialization
type Scalar = str | bool | int | float
type JSONValue = Scalar | Sequence[JSONValue] | Mapping[str, JSONValue] | None
type GitRefState = Literal["prepared", "committed", "aborted"]


def inside_image() -> bool:
    """Check if the current process is in a Bertrand image context.

    Returns
    -------
    bool
        True if we're either building an image or running inside a container process.
        False otherwise.

    Notes
    -----
    If this is true and `inside_container()` is false, then it means the CLI was
    invoked from a Containerfile during an image build, which corresponds to
    ahead-of-time (AoT) compilation for statically-typed languages.  The `build`
    command takes advantage of this to differentiate between normal (in-image) and
    editable (in-container) installs, for example.
    """
    return os.environ.get(BERTRAND_ENV, "") == "1"


def inside_container() -> bool:
    """Check if we're currently running inside a Bertrand container instance.

    Returns
    -------
    bool
        True if we're running inside a container process, False otherwise.
    """
    return all(
        key in os.environ for key in (CONTAINER_ID_ENV, IMAGE_ID_ENV, ENV_ID_ENV)
    )


@dataclass(frozen=True)
class User:
    """A simple structure representing a user identity by user ID and group ID.

    Attributes
    ----------
    uid : int
        The numeric user ID.
    gid : int
        The numeric group ID.
    name : str
        The username.
    home : Path
        The path to the user's home directory.
    """

    uid: int = field(init=False)
    gid: int = field(init=False)
    name: str = field(init=False)
    home: Path = field(init=False)

    def __post_init__(self) -> None:
        """Resolve the effective host user identity."""
        euid = os.geteuid()
        sudo_uid = os.environ.get("SUDO_UID")
        sudo_user = os.environ.get("SUDO_USER")
        if euid == 0 and sudo_uid:
            object.__setattr__(self, 'uid', int(sudo_uid))
            pw = pwd.getpwuid(self.uid)
            object.__setattr__(self, 'gid', pw.pw_gid)
            object.__setattr__(self, 'name', sudo_user or pw.pw_name)
            object.__setattr__(self, 'home', Path(pw.pw_dir))
        else:
            object.__setattr__(self, 'uid', os.getuid())
            pw = pwd.getpwuid(self.uid)
            object.__setattr__(self, 'gid', pw.pw_gid)
            object.__setattr__(self, 'name', pw.pw_name)
            object.__setattr__(self, 'home', Path(pw.pw_dir))


def abspath(path: Path) -> Path:
    """Normalize a filesystem path without resolving symlinks.

    Parameters
    ----------
    path : Path
        The path to normalize.

    Returns
    -------
    Path
        The normalized path.
    """
    return Path(os.path.abspath(path.expanduser()))  # noqa: PTH100


def mkdir_private(path: Path) -> None:
    """Create a directory with private permissions (0700) if it does not already exist.

    Parameters
    ----------
    path : Path
        The path to create.
    """
    path.mkdir(parents=True, exist_ok=True)
    with contextlib.suppress(OSError):
        path.chmod(0o700)


def symlink_points_to(path: Path, target: Path) -> bool:
    """Return whether `path` is a symlink to `target`.

    Parameters
    ----------
    path : Path
        Candidate alias path.
    target : Path
        Expected hidden mount destination.

    Returns
    -------
    bool
        True when `path` is a symlink whose raw target is absolute and exactly
        equal to `target`.
    """
    try:
        if path.is_symlink():
            current = path.readlink()
            return current.is_absolute() and current == target
    except OSError:
        pass
    return False


def atomic_symlink(source: Path, target: Path, *, private: bool = False) -> None:
    """Atomically create a symbolic link, avoiding race conditions and partial writes.

    Parameters
    ----------
    source : Path
        The source path the symbolic link should point to.
    target : Path
        The target path of the symbolic link to create.
    private : bool, optional
        Whether to set private permissions (0600) on the created symlink, by default
        False.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_name(f"{target.name}.tmp.{uuid.uuid4().hex}")
    tmp.symlink_to(source)
    if private:
        tmp.chmod(0o600)
    tmp.replace(target)


def atomic_write_bytes(path: Path, data: bytes, *, private: bool = False) -> None:
    """Atomically write bytes to a file, avoiding race conditions and partial writes.

    Parameters
    ----------
    path : Path
        The path to write to.
    data : bytes
        The bytes to write.
    private : bool, optional
        Whether to set private permissions (0600) on the written file, by default False.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.tmp.{uuid.uuid4().hex}")
    tmp.write_bytes(data)
    with tmp.open("r+b") as f:
        f.flush()
        os.fsync(f.fileno())
    if private:
        tmp.chmod(0o600)
    tmp.replace(path)


def atomic_write_text(
    path: Path,
    text: str,
    encoding: str | None = None,
    *,
    private: bool = False,
) -> None:
    """Atomically write text to a file, avoiding race conditions and partial writes.

    Parameters
    ----------
    path : Path
        The path to write to.
    text : str
        The text to write.
    encoding : str | None, optional
        The text encoding to use (default is None, which uses the system default).
    private : bool, optional
        Whether to set private permissions (0600) on the written file, by default False.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.tmp.{uuid.uuid4().hex}")
    tmp.write_text(text, encoding=encoding)
    with tmp.open("r+", encoding=encoding) as f:
        f.flush()
        os.fsync(f.fileno())
    if private:
        tmp.chmod(0o600)
    tmp.replace(path)


def file_digest(path: Path) -> str:
    """Compute a SHA-256 hex digest for a file.

    Parameters
    ----------
    path : Path
        The path to the file to compute the digest of.

    Returns
    -------
    str
        The SHA-256 hex digest of the file's raw binary contents.
    """
    digest = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)  # 1 MiB chunks
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def tail_lines(path: Path, *, count: int = 40) -> str:
    r"""Return the last `count` lines of a text file.

    Parameters
    ----------
    path : Path
        The path to the text file to read.
    count : int, optional
        The number of lines to return from the end of the file.  Default is 40.  If
        less than 1, then an empty string will be returned.

    Returns
    -------
    str
        The last `count` lines of the file, with newlines normalized to '\n'.
    """
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return ""
    if count < 1:
        return ""
    tail = lines[-count:]
    return "\n".join(tail)


class CompletedProcess(subprocess.CompletedProcess[str]):
    """Format completed subprocess results with command context."""

    def __str__(self) -> str:
        """Return a formatted command result.

        Returns
        -------
        str
            The formatted command result.
        """
        out = [
            f"Exit code {self.returncode} from command:\n\n"
            f"    {' '.join(shlex.quote(a) for a in self.args)}"
        ]
        if self.stderr:
            out.append(self.stderr.strip())
        return "\n\n".join(out)


class CommandError(subprocess.CalledProcessError):
    """Format failed subprocess results with command context."""

    def __str__(self) -> str:
        """Return a formatted command failure.

        Returns
        -------
        str
            The formatted command failure.
        """
        out = [
            f"Exit code {self.returncode} from command:\n\n"
            f"    {' '.join(shlex.quote(a) for a in self.cmd)}"
        ]
        if self.stderr:
            out.append(self.stderr.strip())
        return "\n\n".join(out)


class TimeoutExpired(subprocess.TimeoutExpired, TimeoutError):  # noqa: N818
    """Format subprocess timeouts as standard timeout errors."""

    def __str__(self) -> str:
        """Return a formatted subprocess timeout.

        Returns
        -------
        str
            The formatted timeout error.
        """
        out = [
            f"Command timed out after {self.timeout} seconds:\n\n"
            f"    {' '.join(shlex.quote(a) for a in self.cmd)}"
        ]
        if self.output:
            out.append(self.output.strip())
        if self.stderr:
            out.append(str(self.stderr.strip()))
        return "\n\n".join(out)


def can_escalate() -> bool:
    """Check whether the current system supports privilege escalation.

    Returns
    -------
    bool
        True if privilege escalation is possible on the current system, false
        otherwise.
    """
    return os.name == "posix" and bool(shutil.which("sudo") or shutil.which("doas"))


def confirm(prompt: str, *, assume_yes: bool = False) -> bool:
    """Ask the user for a yes/no confirmation for a given prompt.

    Parameters
    ----------
    prompt : str
        The prompt to display to the user.
    assume_yes : bool, optional
        If True, automatically return True without prompting the user.  Default is
        False.

    Returns
    -------
    bool
        True if the user confirmed yes, false otherwise.
    """
    if assume_yes:
        return True
    try:
        response = input(prompt).strip().lower()
    except EOFError:
        return False
    return response in {"y", "yes"}


async def _run_no_capture(
    argv: list[str],
    proc: asyncio.subprocess.Process,
    timeout: float,
    stdin: str | None,
) -> CompletedProcess | CommandError | None:
    stdin_bytes = None if stdin is None else stdin.encode("utf-8", errors="replace")
    try:
        await asyncio.wait_for(
            proc.communicate(stdin_bytes),
            timeout=None if timeout == INFINITY else timeout,
        )
    except TimeoutError as err:
        proc.kill()
        await proc.communicate()
        raise TimeoutExpired(
            cmd=argv, timeout=timeout or 0.0, output=None, stderr=None
        ) from err

    if proc.returncode is None:
        proc.kill()
        await proc.wait()
        return None

    if proc.returncode == 0:
        return CompletedProcess(argv, proc.returncode, "", "")
    return CommandError(proc.returncode, argv, "", "")


async def _run_capture(
    argv: list[str],
    proc: asyncio.subprocess.Process,
    timeout: float,
    stdin: str | None,
) -> CompletedProcess | CommandError | None:
    stdin_bytes = None if stdin is None else stdin.encode("utf-8", errors="replace")
    try:
        stdout_raw, stderr_raw = await asyncio.wait_for(
            proc.communicate(stdin_bytes),
            timeout=None if timeout == INFINITY else timeout,
        )
    except TimeoutError as err:
        proc.kill()
        stdout_raw, stderr_raw = await proc.communicate()
        raise TimeoutExpired(
            cmd=argv,
            timeout=timeout or 0.0,
            output=stdout_raw.decode("utf-8", errors="replace") or None,
            stderr=stderr_raw.decode("utf-8", errors="replace") or None,
        ) from err

    if proc.returncode is None:
        proc.kill()
        await proc.wait()
        return None

    stdout_text = stdout_raw.decode("utf-8", errors="replace")
    stderr_text = stderr_raw.decode("utf-8", errors="replace")
    if proc.returncode == 0:
        return CompletedProcess(argv, proc.returncode, stdout_text, stderr_text)
    return CommandError(proc.returncode, argv, stdout_text, stderr_text)


async def _tee(
    src: asyncio.StreamReader | None,
    sink: TextIO,
    buf_list: list[str],
) -> None:
    if src is None:
        return
    while True:
        chunk = await src.readline()
        if not chunk:
            break
        text = chunk.decode("utf-8", errors="replace")
        buf_list.append(text)
        try:
            sink.write(text)
            sink.flush()
        except OSError:
            pass


async def _write_stdin(dst: asyncio.StreamWriter | None, data: str) -> None:
    if dst is None:
        return
    try:
        dst.write(data.encode("utf-8", errors="replace"))
        await dst.drain()
    except (BrokenPipeError, ConnectionResetError, OSError):
        pass
    finally:
        try:
            dst.close()
            await dst.wait_closed()
        except (AttributeError, RuntimeError, OSError):
            pass


async def _run_tee(
    argv: list[str],
    proc: asyncio.subprocess.Process,
    timeout: float,
    stdin: str | None,
) -> CompletedProcess | CommandError | None:
    stdout_lines: list[str] = []
    stderr_lines: list[str] = []
    tasks: list[asyncio.Task[None]] = [
        asyncio.create_task(_tee(proc.stdout, sys.stdout, stdout_lines)),
        asyncio.create_task(_tee(proc.stderr, sys.stderr, stderr_lines)),
    ]
    if stdin is not None:
        tasks.append(asyncio.create_task(_write_stdin(proc.stdin, stdin)))

    try:
        try:
            await asyncio.wait_for(
                proc.wait(),
                timeout=None if timeout == INFINITY else timeout,
            )
        except TimeoutError as err:
            proc.kill()
            await proc.wait()
            for task in tasks:
                await task
            stdout_text = "".join(stdout_lines)
            stderr_text = "".join(stderr_lines)
            raise TimeoutExpired(
                cmd=argv,
                timeout=timeout or 0.0,
                output=stdout_text or None,
                stderr=stderr_text or None,
            ) from err
    finally:
        for task in tasks:
            await task

    if proc.returncode is None:
        proc.kill()
        await proc.wait()
        return None

    stdout_text = "".join(stdout_lines)
    stderr_text = "".join(stderr_lines)
    if proc.returncode == 0:
        return CompletedProcess(argv, proc.returncode, stdout_text, stderr_text)
    return CommandError(proc.returncode, argv, stdout_text, stderr_text)


async def run(
    argv: list[str],
    *,
    check: bool = True,
    capture_output: bool | None = False,
    stdin: str | None = None,
    timeout: float = INFINITY,
    attempts: int = 1,
    delay: float = 0.1,
    cwd: Path | None = None,
    env: Mapping[str, str] | None = None,
) -> CompletedProcess:
    """Run a subprocess asynchronously with text-mode error formatting.

    Parameters
    ----------
    argv : list[str]
        The command and its arguments to run.
    check : bool, optional
        Whether to raise a `CommandError` if the command fails (default is True).  If
        false, then any errors will be ignored.
    capture_output : bool | None, optional
        If true, then all output will be redirected to the returned `CompletedProcess`
        or `CommandError`, and excluded from the inherited stdout/stderr streams.  If
        false (the default), then the opposite is the case, and the returned
        `CompletedProcess` or `CommandError` will not include any captured output.  If
        None, then output will be "tee'd" to both the console and the returned objects
        simultaneously.  Note that teeing output in this way may break TTY behavior for
        some commands, and is not recommended for interactive use.
    stdin : str | None, optional
        Input to send to the command's stdin (default is None).
    timeout : float, optional
        An optional timeout in seconds to wait for the command to complete before
        raising a `TimeoutExpired` exception.  Default is infinite, which means to wait
        indefinitely.  If zero or negative, a `TimeoutExpired` exception will be raised
        immediately.  Note that this does not reset between `attempts`, so only the
        overall time spent on retries counts against the timeout.
    attempts : int, optional
        The total number of times to attempt the command.  Defaults to 1, which means
        no retries.  If greater than 1, then any command that exits with a nonzero
        exit code will be re-run after a short delay, up to the specified number
        of times in total.
    delay : float, optional
        The delay in seconds to wait between retries when `attempts` is greater than 1.
        Default is 0.1 seconds.  Must be non-negative.
    cwd : Path | None, optional
        An optional working directory to run the command in.  If None (the default),
        then the current working directory will be used.
    env : Mapping[str, str] | None, optional
        An optional environment dictionary to use for the command.  If None (the
        default), then the current process's environment will be used.

    Returns
    -------
    CompletedProcess
        The completed process result.

    Raises
    ------
    CommandError
        If the command fails and `check` is True.  If `attempts > 1`, then this will
        only reflect the last attempt, and any previous errors will be ignored.
    TimeoutExpired
        If the command does not complete within the specified timeout.
    ValueError
        If `attempts` is less than one or `delay` is negative.
    """
    if attempts < 1:
        msg = "attempts must be at least 1"
        raise ValueError(msg)
    if delay < 0:
        msg = "delay must be non-negative"
        raise ValueError(msg)

    # get overall deadline across attempts
    if timeout <= 0.0:
        raise TimeoutExpired(cmd=argv, timeout=timeout, output=None, stderr=None)
    loop = asyncio.get_running_loop()
    deadline = loop.time() + timeout

    # loop until success, deadline is exceeded, or attempts are exhausted
    last_error: CommandError | None = None
    while attempts > 0:
        proc = await asyncio.create_subprocess_exec(
            *argv,
            stdin=asyncio.subprocess.PIPE if stdin is not None else None,
            stdout=None if capture_output is False else asyncio.subprocess.PIPE,
            stderr=None if capture_output is False else asyncio.subprocess.PIPE,
            cwd=cwd,
            env=env,
        )
        if deadline is not None:
            timeout = deadline - loop.time()

        # capture_output=False -> inherit terminal streams and do not capture output
        result: CompletedProcess | CommandError | None = None
        if capture_output is False:
            result = await _run_no_capture(
                argv,
                proc,
                timeout,
                stdin,
            )

        # capture_output=True -> full capture with no tee
        elif capture_output is True:
            result = await _run_capture(
                argv,
                proc,
                timeout,
                stdin,
            )

        # capture_output=None -> tee streams while capturing for return/errors
        else:
            result = await _run_tee(
                argv,
                proc,
                timeout,
                stdin,
            )

        if isinstance(result, CompletedProcess):
            return result
        last_error = result
        attempts -= 1
        if attempts > 0:
            await asyncio.sleep(delay)

    # exhausted all attempts
    if last_error is not None:
        if check:
            raise last_error
        return CompletedProcess(
            argv,
            last_error.returncode,
            last_error.output or "",
            last_error.stderr or "",
        )
    err = (
        "unspecified error: command did not complete successfully, but no error "
        "information was captured"
    )
    if check:
        raise CommandError(-1, argv, None, err)
    return CompletedProcess(argv, -1, "", err)


def sudo(argv: list[str], *, non_interactive: bool = False) -> list[str]:
    """Return a command with privilege escalation prepended when needed.

    Parameters
    ----------
    argv : list[str]
        The command and its arguments.
    non_interactive : bool, optional
        If True, add non-interactive flags for the selected escalator so it fails
        immediately instead of prompting for a password.

    Returns
    -------
    list[str]
        A new list containing either the original command (when no escalation is
        needed/available) or the escalated command.

    Notes
    -----
    Escalation is only attempted on POSIX systems for non-root users.  The selection
    order is `sudo`, then `doas`.
    """
    # no-op outside POSIX, when already root, or when no supported escalator is found
    if os.name != "posix" or os.geteuid() == 0:
        return argv.copy()
    escalator = None
    if shutil.which("sudo"):
        escalator = "sudo"
    elif shutil.which("doas"):
        escalator = "doas"
    if escalator is None:
        return argv.copy()

    out = [escalator]
    if non_interactive:
        out.append("-n")
    out.extend(argv)
    return out


async def until[T](
    probe: Callable[[float], Awaitable[T]],
    *,
    timeout: float,
    interval: float,
    action: str,
) -> T:
    """Retry an async probe until it succeeds or a timeout expires.

    Parameters
    ----------
    probe : Callable[[float], Awaitable[T]]
        Async function to call with the remaining timeout budget for each attempt.
        Any returned value, including None, is treated as success.
    timeout : float
        Maximum number of seconds to retry before failing.
    interval : float
        Number of seconds to wait between failed probe attempts.  A value of zero
        yields to the event loop before retrying.
    action : str
        Human-readable action used in the timeout error message.

    Returns
    -------
    T
        The value returned by `probe`.

    Raises
    ------
    TimeoutError
        If `timeout` expires before `probe` succeeds.
    ValueError
        If `interval` is negative.
    """
    if timeout <= 0:
        msg = f"timed out {action}"
        raise TimeoutError(msg)
    if interval < 0:
        msg = "interval must be non-negative"
        raise ValueError(msg)

    loop = asyncio.get_running_loop()
    deadline = loop.time() + timeout
    last_error: TimeoutError | subprocess.TimeoutExpired | None = None

    while True:
        remaining = deadline - loop.time()
        if remaining <= 0:
            msg = f"timed out {action}"
            raise TimeoutError(msg) from last_error

        try:
            return await probe(remaining)
        except (TimeoutError, subprocess.TimeoutExpired) as err:
            last_error = err

        remaining = deadline - loop.time()
        if remaining <= 0:
            msg = f"timed out {action}"
            raise TimeoutError(msg) from last_error
        await asyncio.sleep(min(interval, remaining))


def pid_alive(pid: int) -> bool:
    """Check whether a process with the given PID is currently alive on the host system.

    Parameters
    ----------
    pid : int
        The process ID to check.

    Returns
    -------
    bool
        True if a process with the given PID is currently alive, False otherwise.
    """
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return False
    return True


@dataclass(frozen=True)
class _PackageSpec:
    install: list[str]
    refresh: list[str] | None
    yes_install: list[str]
    yes_refresh: list[str]
    noninteractive_env: dict[str, str] | None


_INSTALL_SPECS: dict[str, _PackageSpec] = {
    "apt": _PackageSpec(
        install=["apt-get", "install"],
        refresh=["apt-get", "update"],
        yes_install=["-y"],
        yes_refresh=[],
        noninteractive_env={"DEBIAN_FRONTEND": "noninteractive"},
    ),
    "dnf": _PackageSpec(
        install=["dnf", "install"],
        refresh=["dnf", "makecache"],
        yes_install=["-y"],
        yes_refresh=["-y"],
        noninteractive_env=None,
    ),
    "yum": _PackageSpec(
        install=["yum", "install"],
        refresh=["yum", "makecache"],
        yes_install=["-y"],
        yes_refresh=["-y"],
        noninteractive_env=None,
    ),
    "zypper": _PackageSpec(
        install=["zypper", "install"],
        refresh=["zypper", "refresh"],
        yes_install=["--non-interactive"],
        yes_refresh=["--non-interactive"],
        noninteractive_env=None,
    ),
    "pacman": _PackageSpec(
        install=["pacman", "-S"],
        refresh=["pacman", "-Sy"],
        yes_install=["--noconfirm"],
        yes_refresh=[],
        noninteractive_env=None,
    ),
    "apk": _PackageSpec(
        install=["apk", "add"],
        refresh=["apk", "update"],
        yes_install=["--no-interactive"],
        yes_refresh=["--no-interactive"],
        noninteractive_env=None,
    ),
}


async def install_packages(
    package_manager: str,
    packages: Sequence[str],
    *,
    assume_yes: bool,
    timeout: float,
) -> None:
    """Install OS packages with the requested host package manager.

    Parameters
    ----------
    package_manager : str
        The package manager to use (e.g. "apt", "dnf", etc.).
    packages : Sequence[str]
        The packages to install.
    assume_yes : bool
        If True, automatically confirm any prompts for installation or refreshing
        package lists.  Default is False.
    timeout : float
        An optional timeout in seconds to wait for each package manager command to
        complete before raising a `TimeoutExpired` exception.  If infinite, wait
        indefinitely.  If zero or negative, a `TimeoutExpired` exception will be raised
        immediately.

    Raises
    ------
    OSError
        If the package manager is not supported on the current system.
    PermissionError
        If the package manager requires root privileges and they are not available.
    ValueError
        If the specified package manager is not supported.
    FileNotFoundError
        If the package manager's executable or its refresh command (if applicable) is
        not found in the system PATH.
    TimeoutExpired
        If the package manager command does not complete within the specified timeout.
    """
    if os.name != "posix":
        msg = "package manager operations require a POSIX system."
        raise OSError(msg)
    if os.geteuid() != 0 and not can_escalate():
        msg = (
            f"package installation using {package_manager!r} requires root "
            "privileges; sudo not available."
        )
        raise PermissionError(msg)
    if timeout <= 0.0:
        raise TimeoutExpired(
            cmd=[package_manager],
            timeout=timeout,
            output=None,
            stderr="timed out before command could be started",
        )
    loop = asyncio.get_running_loop()
    deadline = loop.time() + timeout

    # get package manager spec
    spec = _INSTALL_SPECS.get(package_manager)
    if spec is None:
        msg = (
            f"unsupported package manager {package_manager!r} (supported: "
            f"{sorted(_INSTALL_SPECS)})"
        )
        raise ValueError(msg)
    if not shutil.which(spec.install[0]):
        msg = f"package manager {package_manager!r} not found: {spec.install[0]}"
        raise FileNotFoundError(msg)
    if spec.refresh is not None and not shutil.which(spec.refresh[0]):
        msg = f"refresh command not found: {spec.refresh[0]}"
        raise FileNotFoundError(msg)

    # generate environment for non-interactive installs, if needed
    env: dict[str, str] | None = None
    if assume_yes and spec.noninteractive_env:
        env = os.environ.copy()
        env.update(spec.noninteractive_env)

    # refresh package lists if supported
    if spec.refresh is not None:
        cmd = spec.refresh.copy()
        if assume_yes:
            cmd.extend(spec.yes_refresh)
        await run(
            sudo(cmd, non_interactive=assume_yes),
            env=env,
            timeout=deadline - loop.time(),
        )

    # install requested packages
    cmd = spec.install.copy()
    if assume_yes:
        cmd.extend(spec.yes_install)
    cmd.extend(packages)
    await run(
        sudo(cmd, non_interactive=assume_yes), env=env, timeout=deadline - loop.time()
    )


async def download_file(url: str, target: Path, *, retries: int = 3) -> None:
    """Download a file from a URL to a target path, using curl or wget if available.

    Parameters
    ----------
    url : str
        The URL to download from.
    target : Path
        The target path to save the downloaded file to.

    Raises
    ------
    OSError
        If neither curl nor wget is available on the system.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    if shutil.which("curl"):
        await run(
            [
                "curl",
                "-fL",
                "--retry",
                str(retries),
                "--output",
                str(target),
                url,
            ]
        )
    elif shutil.which("wget"):
        await run(
            [
                "wget",
                f"--tries={retries}",
                "--output-document",
                str(target),
                url,
            ]
        )
    else:
        msg = "No download tool available (expected curl or wget)."
        raise OSError(msg)


@dataclass(frozen=True)
class GroupStatus:
    """A simple struct representing a user's membership status in a host group.

    Attributes
    ----------
    configured : bool
        Whether the user is configured as a member of the group (either as a primary or
        secondary member).
    active : bool
        Whether the user's current session is active in the group (i.e. whether the
        group is included in the user's current group list, which is determined at
        login and may need to be refreshed via `newgrp` or a logout/login cycle).
    """

    user: str
    group: str
    configured: bool
    active: bool

    @classmethod
    def get(cls, user: str, group: str) -> Self:
        """Return (configured, active) for user membership in a host group.

        Parameters
        ----------
        user : str
            The username to check for.
        group : str
            The group name to check against.

        Returns
        -------
        GroupStatus
            A GroupStatus object representing the user's membership status.
        """
        try:
            group_info = grp.getgrnam(group)
        except KeyError:
            return cls(user=user, group=group, configured=False, active=False)
        try:
            primary_gid = pwd.getpwnam(user).pw_gid
        except KeyError:
            primary_gid = None
        configured = user in group_info.gr_mem or primary_gid == group_info.gr_gid
        active = (
            group_info.gr_gid in os.getgroups() or os.getegid() == group_info.gr_gid
        )
        return cls(user=user, group=group, configured=configured, active=active)

    async def activate(self, *, assume_yes: bool) -> None:
        """Ensure host group membership.

        Parameters
        ----------
        assume_yes : bool
            If True, automatically confirm any prompts for fixing group membership.

        Raises
        ------
        PermissionError
            If the user declines to update their group membership, or if the update
            requires root privileges and they are not available.
        OSError
            If group membership still isn't properly configured after attempting to
            update it.
        """
        status = self
        if status.configured and status.active:
            return

        # ensure membership
        if not status.configured:
            if not confirm(
                f"Bertrand must add user {status.user!r} to the {status.group!r} "
                f"group in order to avoid future root escalation.  Would you like "
                "Bertrand to add this membership now (requires sudo)?\n[y/N] ",
                assume_yes=assume_yes,
            ):
                msg = f"{status.group} group membership update declined by user."
                raise PermissionError(msg)
            if os.geteuid() != 0 and not can_escalate():
                msg = (
                    f"Updating {status.group} group membership requires root "
                    "privileges; "
                    "sudo not available."
                )
                raise PermissionError(msg)
            await run(
                sudo(
                    ["usermod", "-a", "-G", status.group, status.user],
                    non_interactive=assume_yes,
                )
            )
            status = GroupStatus.get(status.user, status.group)
            if not status.configured:
                msg = f"failed to add user '{status.user}' to group '{status.group}'"
                raise OSError(msg)

        # warn if group membership is not active in current session
        if not status.active:
            print(
                f"bertrand: added {status.user!r} to the {status.group!r} group, but "
                "sudo is still required for this session.  Run "
                f"`newgrp {status.group}` "
                "or log out and back in to pick up the new group privileges before "
                "proceeding.",
                file=sys.stderr,
            )


class HostLock:
    """Provide a re-entrant asynchronous file lock.

    Parameters
    ----------
    path : Path
        Local file path used for host-level locking.
    timeout : float
        The maximum number of seconds to wait for the lock to be acquired before
        raising a `TimeoutError`.  Note that due to the shared lock instances across
        the process, this timeout may be widened by later lock construction for the
        same lock file.  Non-positive timeouts are permitted for opportunistic
        `try_lock()` calls, but blocking `lock()` calls will reject them.
    privileges : int
        The file mode to apply when creating the lock file. Defaults to `0o600`.

    Raises
    ------
    ValueError
        If `privileges` is not a valid file mode.
    OSError
        If the lock path is invalid.
    """

    path: Path
    timeout: float
    privileges: int
    _key: tuple[str, int]
    _fd: int | None
    _owner: asyncio.Task[Any] | None
    _depth: int

    def __new__(  # noqa: D102
        cls,
        path: Path,
        timeout: float,
        *,
        privileges: int = LOCK_DEFAULT_PRIVILEGES,
    ) -> Self:
        path = path.expanduser().resolve()
        if privileges < 0 or privileges > 0o777:
            msg = f"invalid host lock file mode: {oct(privileges)}"
            raise ValueError(msg)
        if path.exists() and path.is_dir():
            msg = (
                f"host lock path must be a file, but a directory already exists: {path}"
            )
            raise OSError(msg)

        # allow re-entrancy with unique lock instances per owning task
        with LOCK_GUARD:
            key = (str(path), privileges)
            self = HOST_LOCKS.get(key)
            if self is None:
                self = super().__new__(cls)
                self.path = path
                self.timeout = timeout
                self.privileges = privileges
                self._key = key
                self._fd = None
                self._owner = None
                self._depth = 0
                HOST_LOCKS[key] = self
            elif self.timeout < timeout:
                self.timeout = timeout
        return cast("Self", self)

    @staticmethod
    def _get_owner() -> asyncio.Task[Any]:
        try:
            task = asyncio.current_task()
        except RuntimeError:
            task = None
        if task is None:
            msg = "HostLock requires an active asyncio Task"
            raise RuntimeError(msg)
        return task

    async def _acquire_file(self, deadline: float) -> bool:
        loop = asyncio.get_running_loop()
        while not await self._try_acquire_file():
            if loop.time() >= deadline:
                return False
            await asyncio.sleep(LOCK_POLL_SECONDS)
        return True

    async def _try_acquire_file(self) -> bool:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        if self._fd is None:
            self._fd = os.open(self.path, os.O_RDWR | os.O_CREAT, self.privileges)
            if hasattr(os, "fchmod"):
                with contextlib.suppress(OSError):
                    os.fchmod(self._fd, self.privileges)

        # Windows file lock on a 1-byte region
        if os.name == "nt":
            os.lseek(self._fd, 0, os.SEEK_SET)
            if os.fstat(self._fd).st_size < 1:
                os.write(self._fd, b"\0")
            try:
                msvcrt.locking(self._fd, msvcrt.LK_NBLCK, 1)
            except OSError as err:
                if err.errno in (errno.EACCES, errno.EDEADLK) or getattr(
                    err, "winerror", None
                ) in {33, 36}:
                    return False
                raise
            return True

        # POSIX non-blocking file lock
        try:
            fcntl.flock(self._fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            return False
        except OSError as err:
            if err.errno in (errno.EACCES, errno.EAGAIN):
                return False
            raise
        return True

    async def _release_file(self) -> None:
        if self._fd is None:
            return
        fd = self._fd
        self._fd = None
        try:
            if os.name == "nt":
                os.lseek(fd, 0, os.SEEK_SET)
                with contextlib.suppress(OSError):
                    msvcrt.locking(fd, msvcrt.LK_UNLCK, 1)
            else:
                with contextlib.suppress(OSError):
                    fcntl.flock(fd, fcntl.LOCK_UN)
        finally:
            os.close(fd)
            with contextlib.suppress(OSError):
                self.path.unlink()

    async def lock(self) -> Self:
        """Acquire this file lock, waiting for this lock's timeout if needed.

        Returns
        -------
        Self
            This lock instance after acquisition.

        Raises
        ------
        TimeoutError
            If the lock cannot be acquired before its timeout.
        """
        if self.timeout <= 0:
            msg = f"could not acquire lock within {self.timeout} seconds"
            raise TimeoutError(msg)

        owner = self._get_owner()
        loop = asyncio.get_running_loop()
        deadline = loop.time() + self.timeout

        # fast-path: same task re-entrancy
        while True:
            with LOCK_GUARD:
                if self._owner is None:
                    self._owner = owner
                    self._depth = 1
                    break
                if self._owner == owner:
                    self._depth += 1
                    return self
            if loop.time() >= deadline:
                msg = f"could not acquire lock within {self.timeout} seconds"
                raise TimeoutError(msg)
            await asyncio.sleep(LOCK_POLL_SECONDS)

        # slow path: acquire via backend
        try:
            if not await self._acquire_file(deadline):
                msg = f"could not acquire lock within {self.timeout} seconds"
                raise TimeoutError(msg)  # noqa: TRY301
            return self  # noqa: TRY300
        except Exception:
            try:
                await self._release_file()
            except Exception:  # noqa: BLE001
                pass
            finally:
                with LOCK_GUARD:
                    self._owner = None
                    self._depth = 0
            raise

    async def try_lock(self) -> bool:
        """Attempt to acquire this lock immediately, without waiting on contention.

        Note that this ignores the lock's timeout, since it is a non-blocking
        operation.

        Returns
        -------
        bool
            `True` if the lock was successfully acquired, or `False` if the lock is
            currently held by another task or process.
        """
        owner = self._get_owner()

        # fast-paths: re-entrant success or immediate contention failure
        with LOCK_GUARD:
            if self._owner == owner:
                self._depth += 1
                return True
            if self._owner is not None:
                return False
            self._owner = owner
            self._depth = 1

        # slow path: single backend attempt only
        try:
            acquired = await self._try_acquire_file()
        except Exception:
            with contextlib.suppress(Exception):
                await self._release_file()
            with LOCK_GUARD:
                if self._owner == owner:
                    self._owner = None
                    self._depth = 0
            raise

        if acquired:
            return True

        with LOCK_GUARD:
            if self._owner == owner:
                self._owner = None
                self._depth = 0
        return False

    async def unlock(self, *, ignore_errors: bool = False) -> None:
        """Release this lock once.  Re-entrant lock depth is decremented.

        Parameters
        ----------
        ignore_errors : bool
            If `True`, suppress any exceptions raised by the backend release operation,
            which may be desirable if the lock is being released in response to an
            error condition and the caller wishes to preserve the original exception.
            Defaults to `False`, in which case backend errors will be raised after
            releasing the lock and clearing lock state.

        Raises
        ------
        RuntimeError
            If the current task does not hold this lock.
        """
        owner = self._get_owner()
        with LOCK_GUARD:
            if self._owner != owner or self._depth < 1:
                msg = "lock is not held by the current owner"
                raise RuntimeError(msg)
            self._depth -= 1
            if self._depth > 0:
                return  # re-entrant case

        try:
            await self._release_file()
        except Exception:
            if not ignore_errors:
                raise
        finally:
            with LOCK_GUARD:
                self._owner = None
                self._depth = 0
                HOST_LOCKS.pop(self._key, None)

    async def __aenter__(self) -> Self:  # noqa: D105
        return await self.lock()

    async def __aexit__(  # noqa: D105
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        await self.unlock(ignore_errors=exc_value is not None)

    def __bool__(self) -> bool:  # noqa: D105
        with LOCK_GUARD:
            return self._depth > 0

    def __repr__(self) -> str:  # noqa: D105
        return f"HostLock(path={self.path!r}, timeout={self.timeout})"


@dataclass(frozen=True)
class GitRefUpdate:
    """A single reference update received from git on stdin."""

    old: str
    new: str
    ref: str

    @property
    def is_head(self) -> bool:
        """Return whether this update targets a branch ref.

        Returns
        -------
        bool
            True if this update targets `refs/heads/*`.
        """
        return self.ref.startswith(GIT_REF_HEADS_PREFIX)

    @property
    def branch(self) -> str:
        """Return the short branch name for this update.

        Returns
        -------
        str
            The short branch name for `refs/heads/*` updates.
        """
        return self.ref[len(GIT_REF_HEADS_PREFIX) :]

    @property
    def created(self) -> bool:
        """Return whether this update created a ref.

        Returns
        -------
        bool
            True if this update created a new ref.
        """
        return all(c == "0" for c in self.old) and any(c != "0" for c in self.new)

    @property
    def destroyed(self) -> bool:
        """Return whether this update deleted a ref.

        Returns
        -------
        bool
            True if this update deleted an existing ref.
        """
        return any(c != "0" for c in self.old) and all(c == "0" for c in self.new)

    @classmethod
    def parse(cls, stdin: str) -> list[GitRefUpdate]:
        """Parse and validate transaction update lines from stdin.

        Parameters
        ----------
        stdin : str
            The raw stdin input containing reference update lines, typically read from
            the `reference-transaction` hook's standard input stream.

        Returns
        -------
        list[GitRefUpdate]
            A list of parsed reference updates.

        Raises
        ------
        ValueError
            If any line is malformed.
        """
        updates: list[GitRefUpdate] = []
        for index, raw in enumerate(stdin.splitlines(), start=1):
            line = raw.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) != 3:
                msg = (
                    f"malformed git transaction line {index}: expected "
                    f"'<old> <new> <ref>', got: {raw!r}"
                )
                raise ValueError(msg)
            old, new, ref = (part.strip() for part in parts)
            if not ref:
                msg = f"malformed git transaction line {index}: ref must not be empty"
                raise ValueError(msg)
            updates.append(cls(old=old, new=new, ref=ref))
        return updates


@dataclass(frozen=True)
class GitRepository:
    """Wrap a Git repository.

    Attributes
    ----------
    git_dir : Path, optional
        The path to the repository's .git directory.  If omitted, the repository will
        be by running `git rev-parse --git-common-dir` in the current working
        directory.
    """

    git_dir: Path

    @property
    def root(self) -> Path:
        """Return the repository root.

        Returns
        -------
        Path
            The absolute path to the repository's root directory, which is the parent of
            the .git directory.
        """
        return self.git_dir.parent

    @property
    def repo_id(self) -> str:
        """Return the stable Bertrand repository identity.

        Returns
        -------
        str
            Stable UUID hex string used to scope cluster resources for the repository.

        Raises
        ------
        OSError
            If Bertrand's host identity is missing or malformed. Run `bertrand init`
            to converge host state before resolving unmanaged repository identities.

        Notes
        -----
        Managed repository metadata takes precedence when present. Otherwise, the ID
        is deterministically derived from the Bertrand host identity and repository
        root path so uninitialized repositories can still address cluster resources
        consistently without colliding with matching paths on other hosts.
        """
        repo_id_file = self.root / METADATA_REPO_ID
        if repo_id_file.is_file():
            try:
                return uuid.UUID(repo_id_file.read_text(encoding="utf-8").strip()).hex
            except (OSError, ValueError):
                pass
        try:
            host_id = uuid.UUID(HOST_ID_FILE.read_text(encoding="utf-8").strip())
        except (OSError, ValueError) as err:
            msg = (
                "Bertrand host identity is missing or malformed. Run `bertrand init` "
                "to converge host state before resolving unmanaged repository IDs."
            )
            raise OSError(msg) from err
        return uuid.uuid5(host_id, self.root.as_posix()).hex

    def __post_init__(self) -> None:  # noqa: D105
        object.__setattr__(self, "git_dir", self.git_dir.expanduser().resolve())

    @classmethod
    async def discover(cls, path: Path | None = None) -> GitRepository | None:
        """Discover the Git repository for the current working directory.

        Parameters
        ----------
        path : Path | None, optional
            An optional path to use as the starting point for discovery.  If None (the
            default), then the current working directory will be used.

        Returns
        -------
        GitRepository | None
            The discovered Git repository, assuming a `path` is inside a Git repository

        """
        result = await run(
            ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
            cwd=path,
            check=False,
            capture_output=True,
        )
        if result.returncode == 0:
            return cls(git_dir=Path(result.stdout.strip()))
        return None

    @classmethod
    async def resolve(cls, path: Path) -> tuple[GitRepository, Path]:
        """Resolve a repository and worktree path.

        Parameters
        ----------
        path : Path
            The input path to resolve a repository and worktree for.  The ancestors
            will be scanned to find the nearest git repository, and the remaining path
            components will be treated as a relative worktree path within the
            repository.  If no repository is found, then the input path will be
            treated as an uninitialized repository, and the worktree will be "."
            (repository-level targeting).  If the path leads to a bare repository,
            then non-root targets must match a registered worktree root exactly.

        Returns
        -------
        tuple[GitRepository, Path]
            A tuple containing the resolved Git repository and the relative worktree
            path within it.  The worktree path is "." for repository-level targets,
            and a non-empty relative path only for explicit worktree targets.  Note
            that the `GitRepository` may be uninitialized if no existing repository
            was found during resolution.

        Raises
        ------
        OSError
            If the resolved repository is bare and does not support relative paths,
            or if a non-root target is not registered as a worktree of the resolved
            repository.
        """
        repo = await cls.discover(path)

        # new bare repository
        if repo is None:
            if not await cls.supports_relative_paths():
                raise OSError(GIT_REQUIRE_RELATIVE_PATHS)
            repo = cls(path / ".git")
            return repo, Path()

        # existing bare repository
        if await repo.is_bare():
            if not await cls.supports_relative_paths():
                raise OSError(GIT_REQUIRE_RELATIVE_PATHS)
            worktree = path.relative_to(repo.root)
            if not worktree.parts:
                return repo, Path()
            if not any(wt.path == path for wt in await repo.worktrees()):
                msg = (
                    f"worktree at {worktree} is not registered as a git worktree of "
                    f"bare repository: {repo.root}"
                )
                raise OSError(msg)
            return repo, worktree

        # existing non-bare repository
        worktree = path.relative_to(repo.root)
        if worktree.parts and not any(wt.path == path for wt in await repo.worktrees()):
            msg = (
                f"nested worktree at {worktree} is not registered as a git worktree "
                f"of non-bare repository: {repo.root}"
            )
            raise OSError(msg)
        return repo, worktree

    def __bool__(self) -> bool:  # noqa: D105
        return (
            self.git_dir.exists()
            and self.git_dir.is_dir()
            and subprocess.run(
                ["git", "--git-dir", str(self.git_dir), "rev-parse", "--git-dir"],
                check=False,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            ).returncode
            == 0
        )

    def __hash__(self) -> int:  # noqa: D105
        return hash(self.git_dir)

    def __eq__(self, other: object) -> bool:  # noqa: D105
        if isinstance(other, GitRepository):
            return self.git_dir == other.git_dir
        return NotImplemented

    async def init(self, *, branch: str | None = None, bare: bool = True) -> None:
        """Initialize a new Git repository at the given path.

        Parameters
        ----------
        branch : str | None, optional
            An optional initial branch name to use for the repository.  If None (the
            default), then the Git installation's default branch will be used (e.g.
            "master" or "main").
        bare : bool, optional
            Whether to create a bare repository (default is True).  If false, then a
            standard repository with a working tree will be created instead.

        """
        self.git_dir.mkdir(parents=True, exist_ok=True)
        cmd = ["git", "init", "--quiet"]
        if branch is not None:
            cmd.extend(["--initial-branch", branch])
        if bare:
            cmd.append("--bare")
        cmd.append(str(self.git_dir))
        await run(cmd)

    async def mirror_from(
        self,
        source: GitRepository,
        *,
        timeout: float,
    ) -> None:
        """Converge this repository from a source using mirror semantics.

        This is a repository-convergence helper, not a generic clone API. It performs
        first-time mirror initialization when the destination is uninitialized, and
        subsequent full-ref mirror updates on reruns.

        Parameters
        ----------
        source : GitRepository
            Source repository whose refs/object graph should be mirrored.
        timeout : float
            Maximum runtime command timeout in seconds.  If infinite, wait
            indefinitely.

        Raises
        ------
        TimeoutError
            If `timeout` is negative.
        OSError
            If the source repository has not been initialized.
        """
        if timeout <= 0:
            msg = "timeout must be non-negative"
            raise TimeoutError(msg)
        if not source:
            msg = (
                f"cannot mirror from uninitialized source repository: {source.git_dir}"
            )
            raise OSError(msg)
        loop = asyncio.get_running_loop()
        deadline = loop.time() + timeout

        # if this is a fresh repository, just clone directly to initialize it
        if not self:
            await run(
                [
                    "git",
                    "clone",
                    "--mirror",
                    str(source.root),
                    str(self.git_dir),
                ],
                capture_output=True,
                timeout=deadline - loop.time(),
            )

        # otherwise, fetch and mirror all refs to converge with the source repository
        else:
            await run(
                [
                    "git",
                    "--git-dir",
                    str(self.git_dir),
                    "fetch",
                    "--prune",
                    str(source.root),
                    "+refs/*:refs/*",
                ],
                capture_output=True,
                timeout=deadline - loop.time(),
            )

    async def run(
        self,
        argv: list[str],
        *,
        check: bool = True,
        capture_output: bool | None = False,
        stdin: str | None = None,
        timeout: float = INFINITY,
        attempts: int = 1,
        delay: float = 0.1,
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
    ) -> CompletedProcess:
        """Run a git command as an asynchronous subprocess wrapper.

        Parameters
        ----------
        argv : list[str]
            The command and its arguments to run, excluding the initial "git".
        check : bool, optional
            Whether to raise a `CommandError` if the command fails (default is True).
            If false, then any errors will be ignored.
        capture_output : bool | None, optional
            If true, then all output will be redirected to the returned
            `CompletedProcess` or `CommandError`, and excluded from the inherited
            stdout/stderr streams.  If false (the default), then the opposite is the
            case, and the returned `CompletedProcess` or `CommandError` will not
            include any captured output.  If None, then output will be "tee'd" to both
            the console and the returned objects simultaneously.  Note that teeing
            output in this way may break TTY behavior for some commands, and is not
            recommended for interactive use.
        stdin : str | None, optional
            Input to send to the command's stdin (default is None).
        timeout : float, optional
            An optional timeout in seconds to wait for the command to complete before
            raising a `TimeoutExpired` exception.  Default is infinite, which means to
            wait indefinitely.  If zero or negative, a `TimeoutExpired` exception will
            be raised immediately.  Note that this does not reset between `attempts`,
            so only the overall time spent on retries counts against the timeout.
        attempts : int, optional
            The total number of times to attempt the command.  Defaults to 1, which
            means no retries.  If greater than 1, then any command that exits with a
            nonzero exit code will be re-run after a short delay, up to the specified
            number of times in total.
        delay : float, optional
            The delay in seconds to wait between retries when `attempts` is greater
            than 1.  Default is 0.1 seconds.  Must be non-negative.
        cwd : Path | None, optional
            An optional working directory to run the command in.  If None (the default),
            then the current working directory will be used.
        env : Mapping[str, str] | None, optional
            An optional environment dictionary to use for the command.  If None (the
            default), then the current process's environment will be used.

        Returns
        -------
        CompletedProcess
            The completed process result.

        """
        return await run(
            ["git", "--git-dir", str(self.git_dir), *argv],
            check=check,
            capture_output=capture_output,
            stdin=stdin,
            timeout=timeout,
            attempts=attempts,
            delay=delay,
            cwd=cwd,
            env=env,
        )

    async def dirty(self) -> bool:
        """Check whether this repository has uncommitted changes.

        Returns
        -------
        bool
            `True` if any checked-out worktree for this repository has uncommitted
            changes, or `False` otherwise. Non-bare repositories are checked directly
            at `self.root`. Bare repositories are checked by scanning every registered
            worktree. Bare repositories with zero worktrees are considered clean.

        """
        if not await self.is_bare():
            result = await self.run(
                ["status", "--porcelain"],
                capture_output=True,
                cwd=self.root,
            )
            return bool(result.stdout.strip())

        # Bare repositories do not have their own worktree; check each attached
        # worktree under a sanitized git environment instead.
        env = await self._strip_env()
        for wt in await self.worktrees():
            result = await run(
                ["git", "-C", str(wt.path), "status", "--porcelain"],
                capture_output=True,
                env=env,
            )
            if result.stdout.strip():
                return True
        return False

    async def git_path(self, path: Path, *, cwd: Path | None = None) -> Path:
        """Resolve a git-path using `git rev-parse --git-path`.

        Parameters
        ----------
        path : str
            The git-path expression to resolve (e.g. `hooks/pre-commit`).
        cwd : Path | None, optional
            Optional working directory for relative path resolution semantics.

        Returns
        -------
        Path
            The resolved absolute filesystem path.

        Raises
        ------
        ValueError
            If git returned an empty path.
        """
        path_str = path.as_posix()
        result = await self.run(
            ["rev-parse", "--path-format=absolute", "--git-path", path_str],
            capture_output=True,
            cwd=cwd,
        )
        text = result.stdout.strip()
        if not text:
            msg = f"empty --git-path output for {path_str!r}"
            raise ValueError(msg)
        resolved = Path(text).expanduser()
        if not resolved.is_absolute():
            base = cwd if cwd is not None else self.root
            resolved = (base / resolved).resolve()
        else:
            resolved = resolved.resolve()
        return resolved

    def _parse_bool(self, stdout: str) -> bool:
        value = stdout.strip().lower()
        if value == "true":
            return True
        if value == "false":
            return False
        msg = f"invalid git boolean output: {stdout!r}"
        raise ValueError(msg)

    @staticmethod
    async def supports_relative_paths() -> bool:
        """Return whether this Git supports relative worktree paths.

        Returns
        -------
        bool
            True if both `git worktree add` and `git worktree move` support
            `--relative-paths` according to their help output, false otherwise.
        """
        add_help = await run(
            ["git", "worktree", "add", "-h"],
            check=False,
            capture_output=True,
        )
        add_text = f"{add_help.stdout}\n{add_help.stderr}".lower()
        if add_help.returncode != 0 or "--relative-paths" not in add_text:
            return False
        move_help = await run(
            ["git", "worktree", "move", "-h"],
            check=False,
            capture_output=True,
        )
        move_text = f"{move_help.stdout}\n{move_help.stderr}".lower()
        return move_help.returncode == 0 and "--relative-paths" in move_text

    @dataclass(frozen=True)
    class Worktree:
        """A parsed entry from `git worktree list --porcelain`.

        Attributes
        ----------
        path : Path
            The absolute path to the worktree checkout.
        branch : str | None
            The short branch name if this worktree is attached to `refs/heads/*`,
            otherwise None.
        """

        path: Path
        branch: str | None = None

        def __post_init__(self) -> None:  # noqa: D105
            object.__setattr__(self, "path", self.path.expanduser().resolve())
            if not self.path.exists():
                msg = f"worktree path does not exist: {self.path}"
                raise FileNotFoundError(msg)
            if not self.path.is_dir():
                msg = f"invalid worktree path: {self.path}"
                raise NotADirectoryError(msg)

    @staticmethod
    async def default_branch() -> str:
        """Return the default Git branch name.

        Returns
        -------
        str
            The default branch name configured for this git installation.

        Raises
        ------
        ValueError
            If the default branch could not be determined from git output.
        """
        branch = await run(["git", "var", "GIT_DEFAULT_BRANCH"], capture_output=True)
        result = branch.stdout.strip()
        if not result:
            msg = "default Git branch name could not be determined"
            raise ValueError(msg)
        return result

    async def head_branch(self) -> str | None:
        """Return the current HEAD branch.

        Returns
        -------
        str | None
            The short branch name of the current HEAD, or None if HEAD is detached.

        Raises
        ------
        CommandError
            If Git returns an unexpected symbolic-ref failure.
        ValueError
            If we failed to parse the output or got an empty branch name.
        """
        # attached HEAD: try to read symbolic ref directly
        result = await self.run(
            ["symbolic-ref", "--quiet", "--short", "HEAD"],
            check=False,
            capture_output=True,
        )
        if result.returncode == 0:
            text = result.stdout.strip()
            if not text:
                msg = "empty symbolic-ref output for HEAD"
                raise ValueError(msg)
            return text
        if result.returncode != 1:
            raise CommandError(
                result.returncode, result.args, result.stdout, result.stderr
            )

        # detached HEAD: let caller decide what to do
        return None

    async def head_worktree(self) -> GitRepository.Worktree | None:
        """Return the in-repository worktree attached to HEAD.

        Returns
        -------
        GitRepository.Worktree | None
            The worktree registered for the current HEAD branch, or None if HEAD is
            detached, unattached, or attached only to an out-of-repository worktree.

        Raises
        ------
        FileExistsError
            If multiple registered worktrees claim the current HEAD branch.
        """
        branch = await self.head_branch()
        if branch is None:
            return None
        matches = [
            worktree
            for worktree in await self.worktrees()
            if worktree.branch == branch and worktree.path.is_relative_to(self.root)
        ]
        if not matches:
            return None
        if len(matches) > 1:
            paths = ", ".join(str(worktree.path) for worktree in matches)
            msg = f"multiple worktrees are attached to HEAD branch {branch!r}: {paths}"
            raise FileExistsError(msg)
        return matches[0]

    async def is_bare(self) -> bool:
        """Return whether this repository is bare.

        Returns
        -------
        bool
            True if this repository is a bare repository, false otherwise.

        Raises
        ------
        ValueError
            If we failed to parse the output.
        """
        result = await self.run(
            ["rev-parse", "--is-bare-repository"],
            capture_output=True,
        )
        value = result.stdout.strip().lower()
        if value == "true":
            return True
        if value == "false":
            return False
        msg = f"invalid --is-bare-repository output: {result.stdout!r}"
        raise ValueError(msg)

    async def branches(self) -> frozenset[str]:
        """Return repository branch names.

        Returns
        -------
        frozenset[str]
            A set of all (short) branch names in the repository.  Note that this only
            includes branches under `refs/heads/`, and not other refs like tags or
            remotes.

        """
        result = await self.run(
            ["for-each-ref", "--format=%(refname:short)", "refs/heads"],
            capture_output=True,
        )
        out = {line.strip() for line in result.stdout.splitlines()}
        out.discard("")  # remove empty lines if any
        return frozenset(out)

    async def worktrees(self) -> tuple[GitRepository.Worktree, ...]:
        """List all local worktrees for the given Git directory.

        Returns
        -------
        tuple[GitRepository.Worktree, ...]
            A tuple of worktree entries.  Includes both attached (with branch) and
            detached (without branch) worktrees, which may be filtered by the caller as
            needed.
        """
        out: list[GitRepository.Worktree] = []
        path: Path | None = None
        branch: str | None = None
        result = await self.run(
            ["worktree", "list", "--porcelain"],
            capture_output=True,
        )
        for raw in result.stdout.splitlines():
            line = raw.strip()
            if not line:
                if path is not None:
                    out.append(self.Worktree(path=path, branch=branch))
                path = None
                branch = None
                continue
            if line.startswith("worktree "):
                path = Path(line[len("worktree ") :]).expanduser().resolve()
                continue
            if line.startswith(f"branch {GIT_REF_HEADS_PREFIX}"):
                branch = line[len("branch ") + len(GIT_REF_HEADS_PREFIX) :]
        if path is not None:
            out.append(self.Worktree(path=path, branch=branch))
        return tuple(out)

    async def _current_worktree_state(self) -> dict[str, Path]:
        current: dict[str, Path] = {}
        for wt in await self.worktrees():
            if wt.branch is None:
                continue
            existing = current.setdefault(wt.branch, wt.path)
            if existing != wt.path:
                msg = (
                    f"multiple worktrees mapped to branch '{wt.branch}': "
                    f"{existing} and {wt.path}"
                )
                raise FileExistsError(msg)
        return current

    def _intended_worktree_changes(
        self, updates: Sequence[GitRefUpdate]
    ) -> tuple[list[str], list[str], list[tuple[str, str]]]:
        # get creation/destruction intent from transaction updates
        created_: dict[str, list[str]] = {}
        destroyed_: dict[str, list[str]] = {}
        created: list[str] = []
        destroyed: list[str] = []
        for update in updates:
            if update.created:
                created.append(update.branch)
                created_.setdefault(update.new, []).append(update.branch)
            elif update.destroyed:
                destroyed.append(update.branch)
                destroyed_.setdefault(update.old, []).append(update.branch)

        # infer rename hints from unambiguous create + destroy pairs on the same object
        renamed: list[tuple[str, str]] = []
        for oid in sorted(set(created_) & set(destroyed_)):
            c = created_[oid]
            d = destroyed_[oid]
            if len(c) == 1 and len(d) == 1:
                old_branch = d[0]
                new_branch = c[0]
                renamed.append((old_branch, new_branch))
                destroyed.remove(old_branch)
                created.remove(new_branch)

        return created, destroyed, renamed

    def _filter_worktree_conflicts(
        self,
        desired: dict[str, Path],
        current: dict[str, Path],
        created: list[str],
    ) -> dict[str, Path]:
        # sort branches by conflict priority, then filter out any whose slash-separated
        # paths would create a nested worktree conflicts
        winners: list[str] = []
        for branch in sorted(
            desired,
            key=lambda b: (
                0 if b in current else 1,  # prioritize existing
                0
                if b not in created
                else 1,  # ... then prioritize non-created branches
                b,  # ... then break ties lexically
            ),
        ):
            conflict: str | None = None
            for winner in winners:
                if branch == winner:
                    continue
                left_parts = branch.split("/")
                right_parts = winner.split("/")
                min_len = min(len(left_parts), len(right_parts))
                if left_parts[:min_len] == right_parts[:min_len]:
                    conflict = winner
                    break
            if conflict is None:
                winners.append(branch)
                continue
            print(
                f"bertrand: skipping branch '{branch}' due nested path conflict with "
                f"'{conflict}'",
                file=sys.stderr,
            )

        return {branch: desired[branch] for branch in winners}

    def _clean_worktree_parents(self, path: Path) -> None:
        # clean up now-empty parent directories up to project root to account for
        # branch names that contain path separators
        cursor = path.parent
        while cursor != self.root:
            try:
                if any(cursor.iterdir()):
                    break
                cursor.rmdir()
            except OSError:
                break
            cursor = cursor.parent

    async def _worktree_belongs_to_repo(self, path: Path, env: dict[str, str]) -> bool:
        result = await run(
            ["git", "-C", str(path), "rev-parse", "--git-common-dir"],
            check=False,
            capture_output=True,
            env=env,
        )
        if result.returncode != 0:
            return False
        owner = Path(result.stdout.strip()).expanduser()
        if not owner.is_absolute():
            owner = path / owner
        return self.git_dir == owner.expanduser().resolve()

    async def _strip_env(self, env: dict[str, str] | None = None) -> dict[str, str]:
        """Remove repo-local git environment variables.

        Parameters
        ----------
        env : dict[str, str] | None, optional
            The environment mapping to strip git variables from.  If None, the current
            process environment will be used.  Defaults to None.

        Returns
        -------
        dict[str, str]
            The filtered environment variables with repo-local keys removed.
        """
        env = dict(os.environ if env is None else env)
        local = await self.run(
            ["rev-parse", "--local-env-vars"], check=False, capture_output=True, env=env
        )
        if local.returncode == 0:
            keys = [key.strip() for key in local.stdout.splitlines() if key.strip()]
        else:
            keys = [
                "GIT_DIR",
                "GIT_WORK_TREE",
                "GIT_COMMON_DIR",
            ]  # best-effort fallback
        for key in keys:
            env.pop(key, None)
        return env

    async def create_worktree(
        self,
        branch: str,
        *,
        target: Path | None = None,
        create_branch: bool = True,
        quiet: bool = False,
    ) -> None:
        """Create a new worktree for the given branch at the specified target path.

        Parameters
        ----------
        branch : str
            The short branch name to create a worktree for.
        target : Path | None, optional
            The target path to create the worktree at.  Must not already exist.
        create_branch : bool, optional
            If True (the default), then the branch will be created if it does not
            already exist.  If False, then the branch must already exist in the
            repository.
        quiet : bool, optional
            If True, then suppress any non-error output from the git command.  Default
            is False.

        Raises
        ------
        FileExistsError
            If the target path already exists.
        """
        if target is None:
            target = self.root / branch
        if target.exists():
            msg = "path already exists"
            raise FileExistsError(msg)
        target.parent.mkdir(parents=True, exist_ok=True)
        cmd = ["worktree", "add", "--relative-paths"]
        if create_branch:
            if branch not in await self.branches():
                cmd.extend(["-b", branch, str(target)])
            else:
                cmd.extend([str(target), branch])
        else:
            cmd.extend([str(target), branch])
        await self.run(cmd, capture_output=quiet)

    async def move_worktree(
        self,
        branch: str,
        *,
        source: Path | None = None,
        target: Path | None = None,
    ) -> None:
        """Move the worktree for a branch.

        Parameters
        ----------
        branch : str
            The short branch name to move the worktree for.
        source : Path | None, optional
            The current path of the worktree to move.  If None, the path will be derived
            from the current worktree state for the given branch.  Defaults to None.
        target : Path | None, optional
            The destination path for the worktree.  If None, the worktree will be moved
            to its default location based on the branch name, if it is not already
            there.  Defaults to None.

        Raises
        ------
        FileNotFoundError
            If the source path does not exist or could not be derived from the current
            worktree state.
        NotADirectoryError
            If the source path or target path exists but is not a directory.
        FileExistsError
            If the target path already exists, and is not the same as the source path.
        """
        if source is None:
            for wt in await self.worktrees():
                if wt.branch == branch:
                    source = wt.path
                    break
            if source is None:
                msg = f"no worktree found for branch '{branch}'"
                raise FileNotFoundError(msg)
        if not source.exists():
            msg = f"worktree path does not exist: {source}"
            raise FileNotFoundError(msg)
        if not source.is_dir():
            msg = f"worktree is not a directory: {source}"
            raise NotADirectoryError(msg)

        if target is None:
            target = self.root / branch
        if target == source:
            return
        if target.exists():
            msg = f"target path already exists: {target}"
            raise FileExistsError(msg)

        target.parent.mkdir(parents=True, exist_ok=True)
        await self.run(
            ["worktree", "move", "--relative-paths", str(source), str(target)],
            capture_output=True,
        )
        self._clean_worktree_parents(source)

    async def destroy_worktree(
        self,
        branch: str,
        *,
        target: Path | None = None,
    ) -> bool:
        """Destroy the worktree for the given branch, if it exists and is clean.

        Parameters
        ----------
        branch : str
            The short branch name to destroy the worktree for.
        target : Path | None, optional
            An optional path to the worktree to destroy.  If None (the default), then
            the path will be derived from the current worktree state for the given
            branch.

        Returns
        -------
        bool
            True if the worktree was successfully destroyed or did not exist, false if
            the worktree exists but could not be destroyed due to dirty state.

        Raises
        ------
        FileNotFoundError
            If the target path does not exist or could not be derived from the current
            worktree state.
        NotADirectoryError
            If the target path exists but is not a directory.
        RuntimeError
            If the target path does not belong to this repository.
        """
        if target is None:
            for wt in await self.worktrees():
                if wt.branch == branch:
                    target = wt.path
                    break
            if target is None:
                msg = f"no worktree found for branch '{branch}'"
                raise FileNotFoundError(msg)
        if not target.exists():
            msg = f"worktree path does not exist: {target}"
            raise FileNotFoundError(msg)
        if not target.is_dir():
            msg = f"worktree is not a directory: {target}"
            raise NotADirectoryError(msg)

        # verify that the worktree is clean and objectively belongs to this repository
        # before attempting deletion
        env = await self._strip_env()
        if not await self._worktree_belongs_to_repo(target, env):
            msg = f"worktree path does not belong to this repository: {target}"
            raise RuntimeError(msg)
        clean = await run(
            ["git", "-C", str(target), "status", "--porcelain"],
            capture_output=True,
            env=env,
        )
        if clean.stdout.strip():
            return False

        # remove the worktree using git, which will also properly clean up the
        # associated gitdir and any linked metadata
        await self.run(["worktree", "remove", str(target)], capture_output=True)
        self._clean_worktree_parents(target)
        return True

    async def sync_worktrees(self, updates: Sequence[GitRefUpdate] = ()) -> None:
        """Converge worktrees to the authoritative branch set.

        Parameters
        ----------
        updates : Sequence[GitRefUpdate], optional
            The parsed reference updates received from git on stdin, which will be used
            to derive explicit intent for branch creations and destructions, as well as
            implicit hints for branch renames where creation and destruction are paired
            on the same object.  If omitted, then convergence will transform directly
            from the current state to the desired state without any intent-based
            guidance.
        """
        # non-bare repositories are treated as single-worktree mode
        if not await self.is_bare():
            return

        # derive current and desired branch-to-path mappings
        current = await self._current_worktree_state()
        desired = {branch: (self.root / branch) for branch in await self.branches()}

        # derive explicit intent from transaction updates, preserving order
        created, destroyed, renamed = self._intended_worktree_changes(updates)
        desired = self._filter_worktree_conflicts(desired, current, created)

        # apply rename hints first (when they map cleanly to current state)
        for old_branch, new_branch in renamed:
            source = current.get(old_branch)
            if source is None:
                continue
            target = desired.get(new_branch)
            if target is None or new_branch in current:
                continue
            try:
                await self.move_worktree(new_branch, source=source, target=target)
                current.pop(old_branch, None)
                current[new_branch] = target
            except Exception as err:  # noqa: BLE001
                print(
                    f"bertrand: failed to move worktree for branch '{new_branch}' from "
                    f"{source} to {target}:\n{err}"
                )

        # apply explicit destroys for branches still present in current state
        for branch in destroyed:
            path = current.get(branch)
            if path is None or branch in desired:
                continue
            try:
                if await self.destroy_worktree(branch, target=path):
                    current.pop(branch, None)
            except Exception as err:  # noqa: BLE001
                print(
                    f"bertrand: failed to destroy worktree for branch '{branch}' at "
                    f"{path}:\n{err}"
                )

        # apply explicit creates for branches that are still missing
        for branch in created:
            if branch in current or branch not in desired:
                continue
            target = desired[branch]
            try:
                await self.create_worktree(branch, target=target, create_branch=True)
                current[branch] = target
            except Exception as err:  # noqa: BLE001
                print(
                    f"bertrand: failed to create worktree for branch '{branch}' at "
                    f"{target}:\n{err}"
                )

        # remove branches no longer present in the repository
        stale = set(current) - set(desired)
        for branch in sorted(stale):
            path = current[branch]
            try:
                if await self.destroy_worktree(branch, target=path):
                    current.pop(branch, None)
            except Exception as err:  # noqa: BLE001
                print(
                    f"bertrand: failed to destroy worktree for branch '{branch}' at "
                    f"{path}:\n{err}"
                )

        # move branches that are present but located at non-canonical paths
        shared = set(current) & set(desired)
        for branch in sorted(shared):
            source = current[branch]
            target = desired[branch]
            if source == target:
                continue
            try:
                await self.move_worktree(branch, source=source, target=target)
                current[branch] = target
            except Exception as err:  # noqa: BLE001
                print(
                    f"bertrand: failed to move worktree for branch '{branch}' from "
                    f"{source} to {target}:\n{err}"
                )

        # create worktrees for branches that don't yet have one
        missing = set(desired) - set(current)
        for branch in sorted(missing):
            target = desired[branch]
            try:
                await self.create_worktree(branch, target=target, create_branch=False)
                current[branch] = target
            except Exception as err:  # noqa: BLE001
                print(
                    f"bertrand: failed to create worktree for branch '{branch}' at "
                    f"{target}:\n{err}"
                )
