name: mypy

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main

jobs:
    mypy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.7
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7
            - name: Install mypy
              run: pip install mypy
            - name: Lint with mypy
              run: mypy --pretty **/*.py
